// Core domain types — ported from the v7 prototype's implicit data shapes.
// `amt` is always stored in the user's base currency; `cur`/`origAmt` hold the
// original foreign amount when an entry was entered in another currency.

export type IO = 'exp' | 'inc' | 'xfer';

export interface Entry {
  id: string;
  ts: number; // epoch ms
  io: IO;
  cat: string; // category key (for xfer: the sentinel 'transfer')
  amt: number; // in base currency (for xfer: the transferred principal)
  note?: string;
  acct?: string; // account id (for xfer: the FROM account)
  acctTo?: string; // xfer only: the TO account
  fee?: number; // xfer only: handling fee, deducted from the FROM account
  discount?: number; // xfer only: bonus credited to the TO account
  subcat?: string;
  cur?: string; // original currency code (if not base)
  origAmt?: number; // original amount in `cur`
  tags?: string[];
  ledger?: string;
  rb?: 'pending' | 'done'; // reimbursement state
  rbAmt?: number;
  refund?: number; // total refunded against this expense
  refundOf?: string; // id of the expense this income refunds
  fromSub?: boolean; // auto-generated by a subscription
  deletedAt?: number | null; // soft delete (tombstone for sync)
  updatedAt?: number; // last-write-wins tiebreaker for sync
  fieldTs?: Record<string, number>; // per-field last-write ms, for field-level merge
}

export interface Account {
  id: string;
  name: string;
  nameEn?: string;
  balance: number; // starting balance
  kind?: 'cash' | 'credit' | 'prepaid'; // default 'cash'; a 'credit' account is a liability
}

export interface Settings {
  budget: number;
  cycleStart: number; // 1..28
  theme: ThemeKey;
  dark?: boolean;
  dailyBudget?: number; // optional per-day spending cap
  catBudgets?: Record<string, number>;
  remindTime?: string;
  lock?: boolean; // require biometric/device auth on launch
  gardenGoal?: number; // flowers to fill the monthly garden wall (default 28)
  aiShareCategories?: boolean; // send category names to the AI parser (default true)
  weeklyBudget?: number; // 周预算
  budgetMode?: 'monthly' | 'weekly'; // 预算模式
  autoBackup?: boolean;
  backupFrequency?: 'daily' | 'weekly';
  maxBackups?: number;
}

export type ThemeKey = 'default' | 'sakura' | 'daisy' | 'jasmine';

export interface Category {
  k: string;
  e: string; // emoji
  zh: string;
  en: string;
  c: string; // accent color
  custom?: boolean;
}

export interface Currencies {
  base: string;
  rates: Record<string, number>; // 1 foreign = rate base
}

export interface Asset {
  id: string;
  name: string;
  type: 'asset' | 'liab';
  val: number;
  noCount?: boolean; // exclude from net-worth total
}

export interface Loan {
  id: string;
  who: string;
  type: 'lend' | 'borrow'; // lend = they owe me; borrow = I owe them
  amt: number;
  repaid?: number;
  ts: number;
}

export interface Sub {
  id: string;
  name: string;
  emoji: string;
  amt: number;
  freq: 'monthly' | 'yearly';
  day: number; // 1..28
  month?: number; // 1..12, charge month for yearly
  cat: string;
  created: number;
  lastCharged?: string; // 'YYYY-M-D' with 0-indexed month (matches v7)
  kind?: 'expense' | 'transfer'; // default 'expense'; 'transfer' auto-posts a 转账
  from?: string; // transfer: FROM account
  to?: string; // transfer: TO account
  periods?: number; // installment: total number of charges (undefined = ongoing subscription)
  charged?: number; // installment: how many charges have fired so far
}

export interface Template {
  id: string;
  io: IO;
  cat: string;
  amt: number;
  note?: string;
  name: string;
}

export interface Tags {
  normal: string[];
  ledger: string[];
}
