// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'store.dart';

// These functions are ignored because they are not marked as `pub`: `view`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

/// Every account, with the balance each one is actually at.
///
/// One call rather than a balance lookup per row: the arithmetic walks the
/// whole ledger once for all of them, and doing it per account would walk it
/// once per account.
List<AccountBalance> balances() =>
    RustLib.instance.api.crateApiAccountsBalances();

/// Every account's balance added together.
double totalBalance() => RustLib.instance.api.crateApiAccountsTotalBalance();

/// The accounts a picker should offer: everything unarchived, plus whichever
/// one is currently selected even when it is archived.
///
/// The exception is the point — editing an old entry that lives on an archived
/// account must not silently move it somewhere else.
List<AccountView> pickable({required String selected}) =>
    RustLib.instance.api.crateApiAccountsPickable(selected: selected);

/// Create an account. Returns its id.
///
/// `id` comes from Dart for the same reason it does on the ledger: generating
/// one reads a clock and a random source, and this crate has neither.
String addAccount({
  required String id,
  required String name,
  required double balance,
  required String kind,
  int? statementDay,
  int? dueDay,
  String? fxCode,
}) => RustLib.instance.api.crateApiAccountsAddAccount(
  id: id,
  name: name,
  balance: balance,
  kind: kind,
  statementDay: statementDay,
  dueDay: dueDay,
  fxCode: fxCode,
);

/// Delete an account, moving everything that referenced it to `default`.
///
/// Returns false for `default` itself, which is not deletable — the ledger
/// would have nowhere to move its entries to.
bool removeAccount({required String id, required PlatformInt64 now}) =>
    RustLib.instance.api.crateApiAccountsRemoveAccount(id: id, now: now);

/// Hide an account from the pickers without touching its history.
///
/// Archiving the *current* account moves the selection back to `default`, so
/// the next record sheet does not open on an account the picker will not show.
bool archiveAccount({required String id, required bool archived}) => RustLib
    .instance
    .api
    .crateApiAccountsArchiveAccount(id: id, archived: archived);

/// An account with its live balance.
class AccountBalance {
  final String id;
  final String name;
  final String? nameEn;

  /// The opening figure the account was created with.
  final double opening;

  /// Opening plus every entry that touched it.
  final double balance;

  /// `"cash" | "credit" | "prepaid" | "fx"`, empty for the default kind.
  final String kind;
  final int? statementDay;
  final int? dueDay;
  final String? fxCode;
  final double? fxRate;
  final bool archived;

  /// True for the one account that cannot be deleted.
  final bool isDefault;

  const AccountBalance({
    required this.id,
    required this.name,
    this.nameEn,
    required this.opening,
    required this.balance,
    required this.kind,
    this.statementDay,
    this.dueDay,
    this.fxCode,
    this.fxRate,
    required this.archived,
    required this.isDefault,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      nameEn.hashCode ^
      opening.hashCode ^
      balance.hashCode ^
      kind.hashCode ^
      statementDay.hashCode ^
      dueDay.hashCode ^
      fxCode.hashCode ^
      fxRate.hashCode ^
      archived.hashCode ^
      isDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountBalance &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          nameEn == other.nameEn &&
          opening == other.opening &&
          balance == other.balance &&
          kind == other.kind &&
          statementDay == other.statementDay &&
          dueDay == other.dueDay &&
          fxCode == other.fxCode &&
          fxRate == other.fxRate &&
          archived == other.archived &&
          isDefault == other.isDefault;
}
