// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'store.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Every entry touching `id`, newest first. Tombstones excluded.
List<AcctRowView> rowsForAccount({required String id}) =>
    RustLib.instance.api.crateApiAcctRowsForAccount(id: id);

/// How many rows an account has, without building them all.
int rowCountForAccount({required String id}) =>
    RustLib.instance.api.crateApiAcctRowCountForAccount(id: id);

/// An entry, and what it did to the balance of the account being viewed.
///
/// The delta is not derivable from the entry alone — the same transfer is
/// negative on one side and positive on the other, by different amounts. That
/// is the whole reason this carries a number rather than letting the screen
/// compute one.
class AcctRowView {
  final EntryView entry;
  final double delta;

  const AcctRowView({required this.entry, required this.delta});

  @override
  int get hashCode => entry.hashCode ^ delta.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AcctRowView &&
          runtimeType == other.runtimeType &&
          entry == other.entry &&
          delta == other.delta;
}
