// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `custom`, `draft_view`, `failure_view`, `live_history`, `load_settings`, `parse_day`, `query_of`, `query_view`, `reset_settings`, `resolved`, `settings_lock`, `settings_value`, `show_day`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Resolved`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

AiSettingsView aiSettings() => RustLib.instance.api.crateApiAiAiSettings();

/// Save the settings. The save notices on its own — see `db::flush_store`.
void setAiSettings({required AiSettingsView view}) =>
    RustLib.instance.api.crateApiAiSetAiSettings(view: view);

/// The base URL a key is served from when none is set: Token Plan keys
/// (`tp-`) have their own cluster. Only the prefix is needed.
String aiDefaultBaseUrl({required String keyPrefix}) =>
    RustLib.instance.api.crateApiAiAiDefaultBaseUrl(keyPrefix: keyPrefix);

String aiDefaultModel() => RustLib.instance.api.crateApiAiAiDefaultModel();

String aiDefaultVisionModel() =>
    RustLib.instance.api.crateApiAiAiDefaultVisionModel();

/// 一句话记账's request. `key_prefix` is the key's first three characters, for
/// the default base only.
AiRequest quickRequest({
  required String text,
  required String today,
  required bool zh,
  required String keyPrefix,
}) => RustLib.instance.api.crateApiAiQuickRequest(
  text: text,
  today: today,
  zh: zh,
  keyPrefix: keyPrefix,
);

/// 拍小票's request. The picture arrives already shrunk by the platform.
AiRequest receiptRequest({
  required String imageBase64,
  required String mime,
  required String today,
  required bool zh,
  required String keyPrefix,
}) => RustLib.instance.api.crateApiAiReceiptRequest(
  imageBase64: imageBase64,
  mime: mime,
  today: today,
  zh: zh,
  keyPrefix: keyPrefix,
);

/// 问账本's request: the question, and nothing of the ledger.
AiRequest askRequest({
  required String question,
  required String today,
  required bool zh,
  required String keyPrefix,
}) => RustLib.instance.api.crateApiAiAskRequest(
  question: question,
  today: today,
  zh: zh,
  keyPrefix: keyPrefix,
);

/// The smallest request that proves the key, the base and the model work.
AiRequest pingRequest({required String keyPrefix}) =>
    RustLib.instance.api.crateApiAiPingRequest(keyPrefix: keyPrefix);

/// 一句话记账, on the phone: no request, no key.
List<DraftView> quickOffline({
  required String text,
  required String today,
  required bool zh,
}) => RustLib.instance.api.crateApiAiQuickOffline(
  text: text,
  today: today,
  zh: zh,
);

/// A reply to 一句话记账 or 拍小票, as drafts. An empty list with no failure is
/// the model finding nothing, which is an answer.
DraftsView draftsReply({
  required int status,
  required String body,
  required String today,
  required bool zh,
}) => RustLib.instance.api.crateApiAiDraftsReply(
  status: status,
  body: body,
  today: today,
  zh: zh,
);

/// A reply to the ping: `None` is working.
FailureView? pingReply({required int status, required String body}) =>
    RustLib.instance.api.crateApiAiPingReply(status: status, body: body);

/// A failure the platform saw before any reply: no connection, or no answer
/// in time.
FailureView networkFailure() => RustLib.instance.api.crateApiAiNetworkFailure();

/// 问账本, on the phone.
AskQueryView askOffline({required String question, required String today}) =>
    RustLib.instance.api.crateApiAiAskOffline(question: question, today: today);

/// A reply to 问账本's request, as a query checked here.
AskReplyView askReply({
  required int status,
  required String body,
  required String today,
}) => RustLib.instance.api.crateApiAiAskReply(
  status: status,
  body: body,
  today: today,
);

/// Run a query over the ledger. `ids` and `days_of` are every live entry and
/// its day in this device's zone — the day is the platform's to decide.
AskAnswerView askRun({
  required AskQueryView query,
  required List<String> ids,
  required List<String> daysOf,
  required String today,
  required bool zh,
}) => RustLib.instance.api.crateApiAiAskRun(
  query: query,
  ids: ids,
  daysOf: daysOf,
  today: today,
  zh: zh,
);

/// `y-m-d`, zero-padded — for a test to compare with what a model is told.
String isoDay({required String day}) =>
    RustLib.instance.api.crateApiAiIsoDay(day: day);

/// One request for the platform to send: where, what, and how long to wait.
/// The key goes in the `Authorization` header, added by the platform.
class AiRequest {
  final String url;
  final String body;
  final int timeoutSecs;

  const AiRequest({
    required this.url,
    required this.body,
    required this.timeoutSecs,
  });

  @override
  int get hashCode => url.hashCode ^ body.hashCode ^ timeoutSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiRequest &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          body == other.body &&
          timeoutSecs == other.timeoutSecs;
}

class AiSettingsView {
  /// Off until the user turns it on. Off, nothing is sent anywhere, and
  /// 一句话记账 and 问账本 still work — on the phone.
  final bool enabled;

  /// Empty: the default for the key — see [`ai_default_base_url`].
  final String baseUrl;

  /// Empty: `mimo-v2.5-pro`.
  final String model;

  /// Empty: `mimo-v2.5`, the one that reads pictures.
  final String visionModel;

  const AiSettingsView({
    required this.enabled,
    required this.baseUrl,
    required this.model,
    required this.visionModel,
  });

  static Future<AiSettingsView> default_() =>
      RustLib.instance.api.crateApiAiAiSettingsViewDefault();

  @override
  int get hashCode =>
      enabled.hashCode ^
      baseUrl.hashCode ^
      model.hashCode ^
      visionModel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiSettingsView &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          baseUrl == other.baseUrl &&
          model == other.model &&
          visionModel == other.visionModel;
}

class AskAnswerView {
  /// As run: a keyword that matched nothing may have become its category.
  final AskQueryView query;

  /// The names of the query's categories, for the chips.
  final List<String> catNames;
  final double value;
  final double total;
  final int count;
  final int days;
  final double sideTotal;
  final double? share;
  final List<AskGroupView> groups;
  final List<AskRowView> top;
  final bool fellBack;

  const AskAnswerView({
    required this.query,
    required this.catNames,
    required this.value,
    required this.total,
    required this.count,
    required this.days,
    required this.sideTotal,
    this.share,
    required this.groups,
    required this.top,
    required this.fellBack,
  });

  @override
  int get hashCode =>
      query.hashCode ^
      catNames.hashCode ^
      value.hashCode ^
      total.hashCode ^
      count.hashCode ^
      days.hashCode ^
      sideTotal.hashCode ^
      share.hashCode ^
      groups.hashCode ^
      top.hashCode ^
      fellBack.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AskAnswerView &&
          runtimeType == other.runtimeType &&
          query == other.query &&
          catNames == other.catNames &&
          value == other.value &&
          total == other.total &&
          count == other.count &&
          days == other.days &&
          sideTotal == other.sideTotal &&
          share == other.share &&
          groups == other.groups &&
          top == other.top &&
          fellBack == other.fellBack;
}

class AskGroupView {
  /// A category key, `y-m-d` or `y-m`.
  final String key;

  /// The category's name, for a category group; the key otherwise.
  final String label;
  final String emoji;
  final String color;
  final double amount;
  final int count;

  const AskGroupView({
    required this.key,
    required this.label,
    required this.emoji,
    required this.color,
    required this.amount,
    required this.count,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      label.hashCode ^
      emoji.hashCode ^
      color.hashCode ^
      amount.hashCode ^
      count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AskGroupView &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label &&
          emoji == other.emoji &&
          color == other.color &&
          amount == other.amount &&
          count == other.count;
}

class AskQueryView {
  /// `y-m-d`, inclusive both ends.
  final String from;
  final String to;
  final String io;
  final List<String> cats;
  final String keyword;

  /// `none`, `category`, `day` or `month`.
  final String group;

  /// `sum`, `count`, `avg_day`, `avg_entry` or `max`.
  final String metric;

  const AskQueryView({
    required this.from,
    required this.to,
    required this.io,
    required this.cats,
    required this.keyword,
    required this.group,
    required this.metric,
  });

  @override
  int get hashCode =>
      from.hashCode ^
      to.hashCode ^
      io.hashCode ^
      cats.hashCode ^
      keyword.hashCode ^
      group.hashCode ^
      metric.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AskQueryView &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          to == other.to &&
          io == other.io &&
          cats == other.cats &&
          keyword == other.keyword &&
          group == other.group &&
          metric == other.metric;
}

class AskReplyView {
  final AskQueryView? query;
  final FailureView? failure;

  const AskReplyView({this.query, this.failure});

  @override
  int get hashCode => query.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AskReplyView &&
          runtimeType == other.runtimeType &&
          query == other.query &&
          failure == other.failure;
}

class AskRowView {
  final String id;
  final String emoji;
  final String name;
  final String note;
  final double amt;
  final String day;

  const AskRowView({
    required this.id,
    required this.emoji,
    required this.name,
    required this.note,
    required this.amt,
    required this.day,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      emoji.hashCode ^
      name.hashCode ^
      note.hashCode ^
      amt.hashCode ^
      day.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AskRowView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          emoji == other.emoji &&
          name == other.name &&
          note == other.note &&
          amt == other.amt &&
          day == other.day;
}

/// One entry, ready to show and to save.
class DraftView {
  final String io;
  final String cat;
  final double amt;
  final String note;

  /// `y-m-d`, when the words named a day; `None` is now.
  final String? day;
  final String emoji;
  final String name;
  final String color;

  const DraftView({
    required this.io,
    required this.cat,
    required this.amt,
    required this.note,
    this.day,
    required this.emoji,
    required this.name,
    required this.color,
  });

  @override
  int get hashCode =>
      io.hashCode ^
      cat.hashCode ^
      amt.hashCode ^
      note.hashCode ^
      day.hashCode ^
      emoji.hashCode ^
      name.hashCode ^
      color.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DraftView &&
          runtimeType == other.runtimeType &&
          io == other.io &&
          cat == other.cat &&
          amt == other.amt &&
          note == other.note &&
          day == other.day &&
          emoji == other.emoji &&
          name == other.name &&
          color == other.color;
}

class DraftsView {
  final List<DraftView> drafts;
  final FailureView? failure;

  const DraftsView({required this.drafts, this.failure});

  @override
  int get hashCode => drafts.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DraftsView &&
          runtimeType == other.runtimeType &&
          drafts == other.drafts &&
          failure == other.failure;
}

/// Why nothing usable came back. `kind` is `network`, `key`, `quota`, `rate`,
/// `request`, `server`, `empty` or `unreadable`; the words for each are Dart's.
class FailureView {
  final String kind;

  /// The service's own message, when it gave one.
  final String detail;

  const FailureView({required this.kind, required this.detail});

  @override
  int get hashCode => kind.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FailureView &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          detail == other.detail;
}
