// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// What a backup taken now is called.
String backupName({required double ts, required bool encrypted}) =>
    RustLib.instance.api.crateApiBackupBackupName(ts: ts, encrypted: encrypted);

/// A directory listing, filtered to backups and sorted newest first.
///
/// The sort matters more than it looks: pruning keeps the first `keep`, so a
/// listing that came back in the wrong order would delete the wrong files.
List<BackupInfoView> listBackups({required List<String> names}) =>
    RustLib.instance.api.crateApiBackupListBackups(names: names);

/// Which files to delete so that `keep` remain. Newest-first input.
List<String> pruneBackups({required List<String> names, required int keep}) =>
    RustLib.instance.api.crateApiBackupPruneBackups(names: names, keep: keep);

/// How many snapshots are kept by default.
int maxBackups() => RustLib.instance.api.crateApiBackupMaxBackups();

/// The document a backup holds: the whole store, stamped.
///
/// `version` is the **app's** schema version and not the file format's — an
/// importer needs to know which shape the ledger is in, which is a different
/// question from which shape the wrapper is in.
///
/// Returns an empty string when the snapshot cannot be produced. Writing a
/// document that *looks* like a backup and holds an empty ledger is worse than
/// writing nothing: the user believes they are covered, and the first restore
/// is the discovery. The caller refuses the empty string.
String buildBackup({required double ts}) =>
    RustLib.instance.api.crateApiBackupBuildBackup(ts: ts);

/// Restore a backup document, replacing the ledger and the config.
///
/// Refuses outright rather than restoring what it can: a document that will not
/// parse says nothing about which half of it was intended, and a ledger half
/// replaced is worse than one not replaced. The same reason `load_entries`
/// answers `-1` instead of loading the rows it managed to read.
RestoreResult restoreBackup({required String json}) =>
    RustLib.instance.api.crateApiBackupRestoreBackup(json: json);

/// One snapshot, as read back off a directory listing.
class BackupInfoView {
  final String name;

  /// Epoch milliseconds. `NaN` when the name carries no usable number — which
  /// sorts last rather than pretending to be a time.
  final double time;
  final bool encrypted;

  const BackupInfoView({
    required this.name,
    required this.time,
    required this.encrypted,
  });

  @override
  int get hashCode => name.hashCode ^ time.hashCode ^ encrypted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupInfoView &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          time == other.time &&
          encrypted == other.encrypted;
}

/// What restoring a document did.
class RestoreResult {
  /// False when the document could not be read at all. Nothing is written in
  /// that case — a half-restored ledger is worse than a refused one.
  final bool ok;

  /// How many rows landed.
  final int entries;

  /// Whether the document carried a config section to restore.
  final bool config;

  const RestoreResult({
    required this.ok,
    required this.entries,
    required this.config,
  });

  @override
  int get hashCode => ok.hashCode ^ entries.hashCode ^ config.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RestoreResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          entries == other.entries &&
          config == other.config;
}
