// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'store.dart';

// These functions are ignored because they are not marked as `pub`: `rows`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`

BatchTally tally({required List<String> ids}) =>
    RustLib.instance.api.crateApiBatchTally(ids: ids);

/// Delete every selected row, newest write last, returning one token each.
///
/// The tokens come back in the order they were taken and go back in the same
/// order. That matters for a refund pair: deleting the expense tombstones its
/// refund income too, and putting them back the other way round would restore
/// an income pointing at a row that is still deleted.
List<UndoToken> removeAll({
  required List<String> ids,
  required PlatformInt64 now,
}) => RustLib.instance.api.crateApiBatchRemoveAll(ids: ids, now: now);

/// Put back what [`remove_all`] took, as fresh stamped writes.
void unremoveAll({required List<UndoToken> undo, required PlatformInt64 now}) =>
    RustLib.instance.api.crateApiBatchUnremoveAll(undo: undo, now: now);

/// Move every selected row on one side of the ledger into a category.
///
/// Returns how many rows were actually written, which is not the size of the
/// selection: rows already in that category are left alone so their `cat`
/// stamp does not jump ahead of another device's real edit.
int categorize({
  required List<String> ids,
  required String io,
  required String cat,
  required PlatformInt64 now,
}) => RustLib.instance.api.crateApiBatchCategorize(
  ids: ids,
  io: io,
  cat: cat,
  now: now,
);

/// Move every selected expense's claim to one state.
///
/// Returns how many rows were written. Income and transfers are not among
/// them and neither are rows already in that state — `core::batch` decides
/// both, and the screen reports the difference so a batch that touched two of
/// four rows says so.
///
/// `Pending` goes through the toggle rather than a patch of its own: the
/// toggle clears a pending claim and sets everything else to pending, and the
/// targets never include a row that is already pending, so it always lands
/// where it was asked to. Using the shipping function is what keeps the
/// stamping rule in one place.
int setClaim({
  required List<String> ids,
  required ClaimTo to,
  required PlatformInt64 now,
}) => RustLib.instance.api.crateApiBatchSetClaim(ids: ids, to: to, now: now);

/// What the selection header says.
class BatchTally {
  final int count;
  final double inc;
  final double exp;

  /// `inc` or `exp` when every selected row is on that side, otherwise
  /// absent. The screen offers 改分类 only when there is one, because a
  /// category belongs to a side and a mixed selection has no answer.
  final String? sharedIo;

  /// How many rows a claim change could touch. The screen offers 报销 only
  /// when this is not zero — reimbursement is an expense's business, and the
  /// rule for that lives in `core::batch`, not in the button.
  final int claimable;

  const BatchTally({
    required this.count,
    required this.inc,
    required this.exp,
    this.sharedIo,
    required this.claimable,
  });

  static Future<BatchTally> default_() =>
      RustLib.instance.api.crateApiBatchBatchTallyDefault();

  @override
  int get hashCode =>
      count.hashCode ^
      inc.hashCode ^
      exp.hashCode ^
      sharedIo.hashCode ^
      claimable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchTally &&
          runtimeType == other.runtimeType &&
          count == other.count &&
          inc == other.inc &&
          exp == other.exp &&
          sharedIo == other.sharedIo &&
          claimable == other.claimable;
}

/// Where a batch is moving the claim state. `Cleared` drops the claim.
enum ClaimTo { pending, done, cleared }
