// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `entries_of`, `parse_day`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`

SettingsView settings() => RustLib.instance.api.crateApiBudgetSettings();

void setSettings({required SettingsView view}) =>
    RustLib.instance.api.crateApiBudgetSetSettings(view: view);

/// The ids that fall inside the cycle containing `today`.
///
/// The cycle is not the calendar month: it turns over on `cycle_start`, so a
/// cycle starting on the 15th runs the 15th to the 14th. Dart supplies each
/// entry's calendar day, as everywhere else.
List<String> cycleIds({
  required List<String> ids,
  required List<String> daysOf,
  required String today,
}) => RustLib.instance.api.crateApiBudgetCycleIds(
  ids: ids,
  daysOf: daysOf,
  today: today,
);

/// The cycle's expense against the cycle's cap.
TierView monthlyStatus({required List<String> ids, required double budget}) =>
    RustLib.instance.api.crateApiBudgetMonthlyStatus(ids: ids, budget: budget);

/// Today's expense against the daily cap.
///
/// `days_of` is parallel to `ids` — each entry's local calendar day, computed
/// by Dart, because projecting an instant onto a day needs a timezone.
TierView dailyStatus({
  required List<String> ids,
  required List<String> daysOf,
  required double dailyBudget,
  required String today,
}) => RustLib.instance.api.crateApiBudgetDailyStatus(
  ids: ids,
  daysOf: daysOf,
  dailyBudget: dailyBudget,
  today: today,
);

/// One row per category that has a cap, closest to its cap first.
///
/// `caps` arrives as two parallel lists because a map has no order across the
/// boundary and this one's order matters: the core applies JavaScript's own key
/// reordering to it, and a cap of zero or less is dropped rather than drawn at
/// zero percent.
List<CatBudgetView> catBudgetRows({
  required List<String> ids,
  required List<String> capCats,
  required List<double> capAmounts,
  required bool zh,
}) => RustLib.instance.api.crateApiBudgetCatBudgetRows(
  ids: ids,
  capCats: capCats,
  capAmounts: capAmounts,
  zh: zh,
);

/// One category with a cap, and how it is doing against it.
class CatBudgetView {
  final String cat;
  final String name;
  final String emoji;

  /// `#RRGGBB`.
  final String color;
  final TierView status;

  const CatBudgetView({
    required this.cat,
    required this.name,
    required this.emoji,
    required this.color,
    required this.status,
  });

  @override
  int get hashCode =>
      cat.hashCode ^
      name.hashCode ^
      emoji.hashCode ^
      color.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CatBudgetView &&
          runtimeType == other.runtimeType &&
          cat == other.cat &&
          name == other.name &&
          emoji == other.emoji &&
          color == other.color &&
          status == other.status;
}

/// The budget settings, as Dart holds them.
///
/// Held on this side for the same reason the ledger is: `tier_status` decides
/// what a cap of zero means, and a second copy of these numbers is a second
/// chance to disagree with it.
class SettingsView {
  /// The cycle's cap. Zero or less is *unset*, not "nothing allowed".
  final double budget;
  final double dailyBudget;

  /// Day of month the cycle turns over, 1..28.
  final int cycleStart;

  /// Parallel to `cap_amounts`, and the order matters — see
  /// [`cat_budget_rows`].
  final List<String> capCats;
  final Float64List capAmounts;

  const SettingsView({
    required this.budget,
    required this.dailyBudget,
    required this.cycleStart,
    required this.capCats,
    required this.capAmounts,
  });

  static Future<SettingsView> default_() =>
      RustLib.instance.api.crateApiBudgetSettingsViewDefault();

  @override
  int get hashCode =>
      budget.hashCode ^
      dailyBudget.hashCode ^
      cycleStart.hashCode ^
      capCats.hashCode ^
      capAmounts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingsView &&
          runtimeType == other.runtimeType &&
          budget == other.budget &&
          dailyBudget == other.dailyBudget &&
          cycleStart == other.cycleStart &&
          capCats == other.capCats &&
          capAmounts == other.capAmounts;
}

/// A spend total against a cap.
class TierView {
  /// The cap, or zero when unset. Never negative.
  final double limit;
  final double used;

  /// `limit - used`, so negative once over.
  final double left;

  /// `used / limit * 100`, or zero when there is no limit. **Not clamped** —
  /// 140% is the number worth showing.
  final double pct;
  final bool over;

  /// True when there is no cap set, which is a different screen from a cap
  /// with nothing spent against it.
  final bool unset;

  const TierView({
    required this.limit,
    required this.used,
    required this.left,
    required this.pct,
    required this.over,
    required this.unset,
  });

  @override
  int get hashCode =>
      limit.hashCode ^
      used.hashCode ^
      left.hashCode ^
      pct.hashCode ^
      over.hashCode ^
      unset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TierView &&
          runtimeType == other.runtimeType &&
          limit == other.limit &&
          used == other.used &&
          left == other.left &&
          pct == other.pct &&
          over == other.over &&
          unset == other.unset;
}
