// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// The burst for `seed` — picked by the platform when the entry is saved.
BurstView petalBurst({required int seed}) =>
    RustLib.instance.api.crateApiBurstPetalBurst(seed: seed);

class BurstView {
  final List<PetalView> petals;

  /// Milliseconds until the last flower has landed.
  final double length;

  const BurstView({required this.petals, required this.length});

  @override
  int get hashCode => petals.hashCode ^ length.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BurstView &&
          runtimeType == other.runtimeType &&
          petals == other.petals &&
          length == other.length;
}

/// One flower of the burst. See `core::burst::Petal`.
class PetalView {
  final double size;

  /// 0 the flower, 1 its soft tint, 2 the leaf, 3 the stamen.
  final int hue;
  final double dx;
  final double rise;

  /// Degrees.
  final double rot;

  /// Milliseconds.
  final double duration;
  final double delay;

  const PetalView({
    required this.size,
    required this.hue,
    required this.dx,
    required this.rise,
    required this.rot,
    required this.duration,
    required this.delay,
  });

  @override
  int get hashCode =>
      size.hashCode ^
      hue.hashCode ^
      dx.hashCode ^
      rise.hashCode ^
      rot.hashCode ^
      duration.hashCode ^
      delay.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PetalView &&
          runtimeType == other.runtimeType &&
          size == other.size &&
          hue == other.hue &&
          dx == other.dx &&
          rise == other.rise &&
          rot == other.rot &&
          duration == other.duration &&
          delay == other.delay;
}
