// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Evaluate a keypad expression. Malformed input answers 0, as it does today.
double evalExpr({required String expr}) =>
    RustLib.instance.api.crateApiCalcEvalExpr(expr: expr);

/// Apply one keypad press to the current expression.
String applyKey({required String expr, required String key}) =>
    RustLib.instance.api.crateApiCalcApplyKey(expr: expr, key: key);

/// Whether the expression carries an operator, which is what decides between
/// showing a running total and showing the typed digits.
bool hasOperator({required String expr}) =>
    RustLib.instance.api.crateApiCalcHasOperator(expr: expr);
