// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_day`, `show_day`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// The cycle containing `anchor`, as a grid.
CalMonthView calendarMonth({
  required List<String> ids,
  required List<String> daysOf,
  required String anchor,
  required String today,
}) => RustLib.instance.api.crateApiCalendarCalendarMonth(
  ids: ids,
  daysOf: daysOf,
  anchor: anchor,
  today: today,
);

/// One day of the grid.
class CalCellView {
  /// `y-m-d`, the key Dart matches its own entries' days against.
  final String day;

  /// The day of the month, for the number in the cell.
  final int dom;

  /// Every entry on the day, transfers included.
  final int count;
  final double exp;
  final double inc;
  final bool today;
  final bool future;

  /// How deep the cell is shaded, 0..1 — `core::calendar::heat`.
  final double heat;

  const CalCellView({
    required this.day,
    required this.dom,
    required this.count,
    required this.exp,
    required this.inc,
    required this.today,
    required this.future,
    required this.heat,
  });

  @override
  int get hashCode =>
      day.hashCode ^
      dom.hashCode ^
      count.hashCode ^
      exp.hashCode ^
      inc.hashCode ^
      today.hashCode ^
      future.hashCode ^
      heat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalCellView &&
          runtimeType == other.runtimeType &&
          day == other.day &&
          dom == other.dom &&
          count == other.count &&
          exp == other.exp &&
          inc == other.inc &&
          today == other.today &&
          future == other.future &&
          heat == other.heat;
}

/// A cycle as a grid.
class CalMonthView {
  final String start;
  final String last;

  /// Blank cells before the first day, Monday-first.
  final int leading;
  final List<CalCellView> cells;
  final double exp;
  final double inc;

  /// Whether › may page to the next cycle.
  final bool canForward;

  const CalMonthView({
    required this.start,
    required this.last,
    required this.leading,
    required this.cells,
    required this.exp,
    required this.inc,
    required this.canForward,
  });

  @override
  int get hashCode =>
      start.hashCode ^
      last.hashCode ^
      leading.hashCode ^
      cells.hashCode ^
      exp.hashCode ^
      inc.hashCode ^
      canForward.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalMonthView &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          last == other.last &&
          leading == other.leading &&
          cells == other.cells &&
          exp == other.exp &&
          inc == other.inc &&
          canForward == other.canForward;
}
