// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `already_seen`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Work out what the queue would add to the ledger and to the inbox.
///
/// `waiting_*` are the drafts already sitting in the inbox from an earlier
/// drain, passed in parallel arrays because they live on the Dart side. They
/// count as already-represented payments: a follow-up push for something the
/// user has not confirmed yet must not queue twice.
///
/// Account and ledger are left unset on purpose. A notification says nothing
/// about which account paid, and guessing "whatever was last used" silently
/// corrupts account balances.
DrainPlan planDrain({
  required List<RawNotifView> raws,
  required List<String> waitingIo,
  required List<double> waitingAmt,
  required Int64List waitingTs,
}) => RustLib.instance.api.crateApiCapturePlanDrain(
  raws: raws,
  waitingIo: waitingIo,
  waitingAmt: waitingAmt,
  waitingTs: waitingTs,
);

/// Write captured payments to the ledger in one go. Returns how many landed.
///
/// Tagged `src: notif`, which is what lets a later drain know these rows
/// already stand for those payments. Account and ledger stay unset: a
/// notification does not say which account paid, and a guess would corrupt a
/// balance silently.
int postCaptured({
  required List<String> io,
  required List<String> cat,
  required List<double> amt,
  required List<String> note,
  required Int64List ts,
  required List<String> ids,
  required PlatformInt64 now,
}) => RustLib.instance.api.crateApiCapturePostCaptured(
  io: io,
  cat: cat,
  amt: amt,
  note: note,
  ts: ts,
  ids: ids,
  now: now,
);

/// A payment ready to become an entry.
class DraftView {
  final String io;
  final String cat;
  final double amt;
  final String note;
  final PlatformInt64 ts;

  const DraftView({
    required this.io,
    required this.cat,
    required this.amt,
    required this.note,
    required this.ts,
  });

  @override
  int get hashCode =>
      io.hashCode ^ cat.hashCode ^ amt.hashCode ^ note.hashCode ^ ts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DraftView &&
          runtimeType == other.runtimeType &&
          io == other.io &&
          cat == other.cat &&
          amt == other.amt &&
          note == other.note &&
          ts == other.ts;
}

/// What draining the queue would do. Nothing has happened yet.
class DrainPlan {
  /// Confident captures: a merchant name came through, so the note means
  /// something and the row can post unattended.
  final List<DraftView> posted;
  final List<PendingView> pending;
  final List<UnparsedView> unparsed;

  /// Every id handed in, including the ones that became nothing. A duplicate
  /// push is still handled — leaving it in the queue would re-examine it on
  /// every drain forever.
  final List<String> consumed;

  const DrainPlan({
    required this.posted,
    required this.pending,
    required this.unparsed,
    required this.consumed,
  });

  @override
  int get hashCode =>
      posted.hashCode ^
      pending.hashCode ^
      unparsed.hashCode ^
      consumed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrainPlan &&
          runtimeType == other.runtimeType &&
          posted == other.posted &&
          pending == other.pending &&
          unparsed == other.unparsed &&
          consumed == other.consumed;
}

/// A parsed payment that was not confident enough to post unattended.
class PendingView {
  /// The native queue id, so a decision can name the row it came from.
  final String id;
  final String source;

  /// What the notification actually said, for the confirm sheet. A user
  /// asked to accept a guess deserves to see what it was a guess about.
  final String raw;
  final DraftView draft;

  const PendingView({
    required this.id,
    required this.source,
    required this.raw,
    required this.draft,
  });

  @override
  int get hashCode =>
      id.hashCode ^ source.hashCode ^ raw.hashCode ^ draft.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          source == other.source &&
          raw == other.raw &&
          draft == other.draft;
}

/// One row out of the native queue.
class RawNotifView {
  final String id;
  final String pkg;
  final String? title;
  final String? text;
  final String? bigText;
  final PlatformInt64 postedAt;

  const RawNotifView({
    required this.id,
    required this.pkg,
    this.title,
    this.text,
    this.bigText,
    required this.postedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      pkg.hashCode ^
      title.hashCode ^
      text.hashCode ^
      bigText.hashCode ^
      postedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RawNotifView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pkg == other.pkg &&
          title == other.title &&
          text == other.text &&
          bigText == other.bigText &&
          postedAt == other.postedAt;
}

/// A capture from a watched app that no rule understood.
///
/// Kept on purpose. Notification wording differs by app version, bank and
/// region, and there is no way to write rules for text nobody has seen — this
/// is how the real strings on a real phone become visible.
class UnparsedView {
  final String id;
  final String pkg;
  final String raw;
  final PlatformInt64 postedAt;

  const UnparsedView({
    required this.id,
    required this.pkg,
    required this.raw,
    required this.postedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ pkg.hashCode ^ raw.hashCode ^ postedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnparsedView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pkg == other.pkg &&
          raw == other.raw &&
          postedAt == other.postedAt;
}
