// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `as_str`, `inbox_lock`, `parse_source`, `pending_view`, `post`, `unparsed_view`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Drain the native queue: classify, record what is confident, keep the rest.
///
/// Writes before returning, deliberately — Dart acknowledges the native queue
/// after this call, and nothing may sit between the decision and the row
/// reaching the ledger.
DrainSummary drainCaptures({
  required List<RawNotifView> raws,
  required PlatformInt64 now,
}) => RustLib.instance.api.crateApiCaptureDrainCaptures(raws: raws, now: now);

List<PendingView> inboxPending() =>
    RustLib.instance.api.crateApiCaptureInboxPending();

List<UnparsedView> inboxUnparsed() =>
    RustLib.instance.api.crateApiCaptureInboxUnparsed();

/// Accept a waiting payment.
///
/// False for an id that is no longer queued, which is a no-op rather than an
/// error: the caller is a screen that may be acting on a row a later drain has
/// since resolved.
bool confirmPending({required String id, required PlatformInt64 now}) =>
    RustLib.instance.api.crateApiCaptureConfirmPending(id: id, now: now);

void dismissPending({required String id}) =>
    RustLib.instance.api.crateApiCaptureDismissPending(id: id);

void clearUnparsed() => RustLib.instance.api.crateApiCaptureClearUnparsed();

/// Everything the inbox holds, for the file that carries it across a restart.
String inboxBlob() => RustLib.instance.api.crateApiCaptureInboxBlob();

/// Read the inbox back. False for a document that cannot be read at all.
///
/// Unlike the ledger, a failure here is not something to refuse over: every
/// item is either replaceable from the wallet's own export or was never going
/// to become an entry. It starts empty and says so.
bool loadInbox({required String json}) =>
    RustLib.instance.api.crateApiCaptureLoadInbox(json: json);

/// How many unparsed captures are kept. Asked rather than restated, so a test
/// that checks the bound is checking the core's bound and not a copy of it.
int maxUnparsed() => RustLib.instance.api.crateApiCaptureMaxUnparsed();

/// Forget everything the inbox holds. For tests, which share one process.
void resetInbox() => RustLib.instance.api.crateApiCaptureResetInbox();

/// What one drain did.
class DrainSummary {
  /// Added to the ledger outright.
  final int posted;

  /// Parsed, but waiting for a tap.
  final int queued;
  final int unparsed;

  const DrainSummary({
    required this.posted,
    required this.queued,
    required this.unparsed,
  });

  @override
  int get hashCode => posted.hashCode ^ queued.hashCode ^ unparsed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrainSummary &&
          runtimeType == other.runtimeType &&
          posted == other.posted &&
          queued == other.queued &&
          unparsed == other.unparsed;
}

/// A parsed payment that was not confident enough to post unattended.
class PendingView {
  /// The native queue id, so a decision can name the row it came from.
  final String id;
  final String source;

  /// What the notification actually said, for the confirm sheet. A user
  /// asked to accept a guess deserves to see what it was a guess about.
  final String raw;
  final String io;
  final String cat;
  final double amt;
  final String note;
  final PlatformInt64 ts;

  const PendingView({
    required this.id,
    required this.source,
    required this.raw,
    required this.io,
    required this.cat,
    required this.amt,
    required this.note,
    required this.ts,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      source.hashCode ^
      raw.hashCode ^
      io.hashCode ^
      cat.hashCode ^
      amt.hashCode ^
      note.hashCode ^
      ts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          source == other.source &&
          raw == other.raw &&
          io == other.io &&
          cat == other.cat &&
          amt == other.amt &&
          note == other.note &&
          ts == other.ts;
}

/// One row out of the native queue.
class RawNotifView {
  final String id;
  final String pkg;
  final String? title;
  final String? text;
  final String? bigText;
  final PlatformInt64 postedAt;

  const RawNotifView({
    required this.id,
    required this.pkg,
    this.title,
    this.text,
    this.bigText,
    required this.postedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      pkg.hashCode ^
      title.hashCode ^
      text.hashCode ^
      bigText.hashCode ^
      postedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RawNotifView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pkg == other.pkg &&
          title == other.title &&
          text == other.text &&
          bigText == other.bigText &&
          postedAt == other.postedAt;
}

/// A capture from a watched app that no rule understood.
class UnparsedView {
  final String id;
  final String pkg;
  final String raw;
  final PlatformInt64 postedAt;

  const UnparsedView({
    required this.id,
    required this.pkg,
    required this.raw,
    required this.postedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ pkg.hashCode ^ raw.hashCode ^ postedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnparsedView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pkg == other.pkg &&
          raw == other.raw &&
          postedAt == other.postedAt;
}
