// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `custom_of`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`, `from`

/// Every category for one direction, in picker order: built-ins then custom.
List<CategoryView> allCats({
  required String io,
  required List<CategoryView> custom,
}) => RustLib.instance.api.crateApiCatalogAllCats(io: io, custom: custom);

/// Look up one category. Never fails: an unknown key falls back to the last.
CategoryView catOf({
  required String io,
  required String key,
  required List<CategoryView> custom,
}) =>
    RustLib.instance.api.crateApiCatalogCatOf(io: io, key: key, custom: custom);

/// A category's name in the caller's language.
String catName({required CategoryView cat, required bool zh}) =>
    RustLib.instance.api.crateApiCatalogCatName(cat: cat, zh: zh);

CatLabel catLabel({
  required String io,
  required String key,
  required bool zh,
  required List<CategoryView> custom,
}) => RustLib.instance.api.crateApiCatalogCatLabel(
  io: io,
  key: key,
  zh: zh,
  custom: custom,
);

/// The lookup and the naming in one call, which is what a list row wants.
///
/// A row draws four things and a round trip per row per rebuild is four times
/// more boundary crossing than it needs. This is one.
class CatLabel {
  final String emoji;
  final String name;

  /// `#RRGGBB`.
  final String color;

  const CatLabel({
    required this.emoji,
    required this.name,
    required this.color,
  });

  @override
  int get hashCode => emoji.hashCode ^ name.hashCode ^ color.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CatLabel &&
          runtimeType == other.runtimeType &&
          emoji == other.emoji &&
          name == other.name &&
          color == other.color;
}

/// A category, as Dart holds it.
class CategoryView {
  final String k;

  /// Emoji.
  final String e;
  final String zh;
  final String en;

  /// Accent colour, `#RRGGBB`.
  final String c;
  final bool custom;

  const CategoryView({
    required this.k,
    required this.e,
    required this.zh,
    required this.en,
    required this.c,
    required this.custom,
  });

  @override
  int get hashCode =>
      k.hashCode ^
      e.hashCode ^
      zh.hashCode ^
      en.hashCode ^
      c.hashCode ^
      custom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CategoryView &&
          runtimeType == other.runtimeType &&
          k == other.k &&
          e == other.e &&
          zh == other.zh &&
          en == other.en &&
          c == other.c &&
          custom == other.custom;
}
