// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `base_code`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

/// The base, and every rate against it, sorted by code.
///
/// Sorted because a `HashMap` has no order and a list that reshuffled itself
/// between two reads of the same table would read as a bug.
List<RateView> rates() => RustLib.instance.api.crateApiCurrencyRates();

String baseCurrency() => RustLib.instance.api.crateApiCurrencyBaseCurrency();

/// Set or overwrite one rate.
///
/// No validation here on purpose: the screen owns what a sensible number is,
/// and [`set_base_currency`] refuses anything unusable at the point it matters.
void setRate({required String code, required double rate}) =>
    RustLib.instance.api.crateApiCurrencySetRate(code: code, rate: rate);

/// Start tracking a code, at parity.
///
/// A code already sitting at **zero** counts as missing and is reset to one —
/// `if (!rates[code])` is a truthiness test, and a rate of zero is not a rate.
void addRate({required String code}) =>
    RustLib.instance.api.crateApiCurrencyAddRate(code: code);

void removeRate({required String code}) =>
    RustLib.instance.api.crateApiCurrencyRemoveRate(code: code);

/// What a base switch did: `ok` | `same` | `noRate`.
String setBaseCurrency({required String code, required PlatformInt64 now}) =>
    RustLib.instance.api.crateApiCurrencySetBaseCurrency(code: code, now: now);

/// The codes the picker offers, and what each is called.
///
/// The core answers `None` for a code it has no name for, and the picker only
/// ever offers ones it does — so the list is built from the codes rather than
/// filtered afterwards.
List<RateView> knownCurrencies() =>
    RustLib.instance.api.crateApiCurrencyKnownCurrencies();

/// The display name for a code — `人民币 ¥` — or the code itself when the core
/// has no name for it.
String currencyName({required String code}) =>
    RustLib.instance.api.crateApiCurrencyCurrencyName(code: code);

/// One tracked currency and what it is worth.
class RateView {
  final String code;

  /// 1 `code` = this many of the base.
  final double rate;

  /// `￥`, `$`… or the code itself when there is no symbol for it.
  final String symbol;
  final bool isBase;

  const RateView({
    required this.code,
    required this.rate,
    required this.symbol,
    required this.isBase,
  });

  @override
  int get hashCode =>
      code.hashCode ^ rate.hashCode ^ symbol.hashCode ^ isBase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RateView &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          rate == other.rate &&
          symbol == other.symbol &&
          isBase == other.isBase;
}
