// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `entries_to_json`, `handle`, `mark_all`, `mark_config`, `mark_many`, `mark`, `say`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Handle`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// Open (or create) the ledger database at `path`.
///
/// Returns `""` on success. An existing file from a newer build is refused
/// here rather than opened, so the caller can say so instead of the app
/// quietly dropping fields it does not know about on the next save.
String openStore({required String path}) =>
    RustLib.instance.api.crateApiDbOpenStore(path: path);

bool storeIsOpen() => RustLib.instance.api.crateApiDbStoreIsOpen();

/// Close the database, discarding nothing — a flush is the caller's job.
void closeStore() => RustLib.instance.api.crateApiDbCloseStore();

/// The schema version of the open database, or of a fresh one when none is
/// open. `-1` if SQLite itself could not be reached.
int storeSchemaVersion() => RustLib.instance.api.crateApiDbStoreSchemaVersion();

/// Read the database into the in-memory store.
///
/// Returns the number of entries, or `-1` with the message in `last_error`
/// when the file could not be read. The distinction matters the same way it
/// did for the JSON files: an empty database is a first launch, and an
/// unreadable one is a thing the caller must not save over.
PlatformInt64 loadFromStore() => RustLib.instance.api.crateApiDbLoadFromStore();

/// How many entry rows a save would write right now.
///
/// `-1` means "all of them" — a bulk change is pending. Exposed so a test can
/// assert that editing one entry writes one row, which is the entire reason
/// this file exists.
PlatformInt64 dirtyEntryCount() =>
    RustLib.instance.api.crateApiDbDirtyEntryCount();

/// Write everything outstanding. `""` on success.
String flushStore() => RustLib.instance.api.crateApiDbFlushStore();

/// Has a legacy import already been done against this database?
bool alreadyMigrated() => RustLib.instance.api.crateApiDbAlreadyMigrated();

/// Import the old `entries.json` / `config.json` contents, once.
///
/// Returns `""` on success. Either string may be empty for a file that did not
/// exist; an entries document that cannot be read is refused outright rather
/// than partially imported, because a lenient parse of a truncated array
/// recovers whichever rows happen to be complete and calls the rest gone.
///
/// The caller keeps the JSON files afterwards. Deleting the only copy of a
/// ledger on the first run of new storage code is not a thing to do, however
/// well this is tested.
String migrateFromJson({
  required String entriesJson,
  required String configJson,
}) => RustLib.instance.api.crateApiDbMigrateFromJson(
  entriesJson: entriesJson,
  configJson: configJson,
);

/// The whole ledger as JSON, for a caller that wants the bytes rather than the
/// database — the backup export, and nothing else.
String storeSnapshot() => RustLib.instance.api.crateApiDbStoreSnapshot();

/// Reclaim space. Slow; never on a save path.
String compactStore() => RustLib.instance.api.crateApiDbCompactStore();

/// Forget the open database and everything pending. For tests, which share one
/// process and must not leak a handle from one case into the next.
void resetStoreHandle() => RustLib.instance.api.crateApiDbResetStoreHandle();

/// The schema this build writes, without touching SQLite.
int supportedSchemaVersion() =>
    RustLib.instance.api.crateApiDbSupportedSchemaVersion();
