// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_day`

/// The whole ledger as CSV **bytes**, oldest first.
///
/// Bytes and not a `String`, for a reason worth stating: Dart's `Utf8Decoder`
/// strips a leading BOM, so the U+FEFF the core writes cannot survive crossing
/// as a string — it would arrive silently gone and the file would open in
/// Excel as mojibake. An export is a file anyway, and a file is bytes.
///
/// `ids` and `days_of` are parallel: each entry's local calendar day, resolved
/// by Dart. Passing the ids rather than whole entries keeps this a projection
/// of state the store already owns.
///
/// Tombstones are dropped by the core: an export states what the ledger holds,
/// not what it has ever held.
Uint8List exportCsv({
  required List<String> ids,
  required List<String> daysOf,
}) => RustLib.instance.api.crateApiExportExportCsv(ids: ids, daysOf: daysOf);
