// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `theme`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

/// 感知环境颜色 — the wash a surface should paint over a given colour.
///
/// Returns a finished `rgba(...)`. Flutter parses it once rather than
/// recomputing the mix, which is the whole point of the arithmetic living in
/// Rust: a `color-mix` in a stylesheet needs a browser, and four numbers need
/// nothing.
String washColor({
  required bool isDark,
  required String card,
  required String paper,
  required GlassLevel level,
  String? under,
  double? alpha,
  String? surface,
}) => RustLib.instance.api.crateApiGlassWashColor(
  isDark: isDark,
  card: card,
  paper: paper,
  level: level,
  under: under,
  alpha: alpha,
  surface: surface,
);

/// 根据内容属性自动调整通透度.
double readabilityAlpha({
  required bool isDark,
  required GlassLevel level,
  required double density,
  required GlassTier tier,
}) => RustLib.instance.api.crateApiGlassReadabilityAlpha(
  isDark: isDark,
  level: level,
  density: density,
  tier: tier,
);

GlassSpec glassSpec({required bool isDark, required GlassLevel level}) =>
    RustLib.instance.api.crateApiGlassGlassSpec(isDark: isDark, level: level);

GlassTier resolveTier({
  required bool reduceTransparency,
  required bool isWeb,
}) => RustLib.instance.api.crateApiGlassResolveTier(
  reduceTransparency: reduceTransparency,
  isWeb: isWeb,
);

/// 感知交互行为 — the bloom that answers a touch.
String touchLightColor({required bool isDark}) =>
    RustLib.instance.api.crateApiGlassTouchLightColor(isDark: isDark);

/// Relative luminance, exposed because the UI decides content density from it.
double luminance({required String hex}) =>
    RustLib.instance.api.crateApiGlassLuminance(hex: hex);

/// Where a glass surface sits in the stack.
enum GlassLevel { chrome, sheet, card }

/// The per-level constants, as Dart can hold them. `edge` widens from
/// `&'static str` to `String` because a borrowed lifetime cannot cross.
class GlassSpec {
  final double intensity;
  final double washAlpha;
  final double washAlphaFlat;
  final double sheen;
  final double sheenHeight;
  final String edge;

  /// Negative means "the platform's hairline" — Flutter substitutes
  /// `1 / devicePixelRatio`, the way `StyleSheet.hairlineWidth` did.
  final double edgeWidth;

  const GlassSpec({
    required this.intensity,
    required this.washAlpha,
    required this.washAlphaFlat,
    required this.sheen,
    required this.sheenHeight,
    required this.edge,
    required this.edgeWidth,
  });

  @override
  int get hashCode =>
      intensity.hashCode ^
      washAlpha.hashCode ^
      washAlphaFlat.hashCode ^
      sheen.hashCode ^
      sheenHeight.hashCode ^
      edge.hashCode ^
      edgeWidth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlassSpec &&
          runtimeType == other.runtimeType &&
          intensity == other.intensity &&
          washAlpha == other.washAlpha &&
          washAlphaFlat == other.washAlphaFlat &&
          sheen == other.sheen &&
          sheenHeight == other.sheenHeight &&
          edge == other.edge &&
          edgeWidth == other.edgeWidth;
}

/// How much of the material a device can actually render.
enum GlassTier { full, wash, solid }
