// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `theme`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

/// 感知环境颜色 — the wash a surface should paint over a given colour.
///
/// Returns a finished `rgba(...)`. Flutter parses it once rather than
/// recomputing the mix, which is the whole point of the arithmetic living in
/// Rust: a `color-mix` in a stylesheet needs a browser, and four numbers need
/// nothing.
String washColor({
  required bool isDark,
  required String card,
  required String paper,
  required GlassLevel level,
  String? under,
  double? alpha,
  String? surface,
}) => RustLib.instance.api.crateApiGlassWashColor(
  isDark: isDark,
  card: card,
  paper: paper,
  level: level,
  under: under,
  alpha: alpha,
  surface: surface,
);

/// 根据内容属性自动调整通透度.
double readabilityAlpha({
  required bool isDark,
  required GlassLevel level,
  required double density,
  required GlassTier tier,
}) => RustLib.instance.api.crateApiGlassReadabilityAlpha(
  isDark: isDark,
  level: level,
  density: density,
  tier: tier,
);

GlassSpec glassSpec({required bool isDark, required GlassLevel level}) =>
    RustLib.instance.api.crateApiGlassGlassSpec(isDark: isDark, level: level);

GlassTier resolveTier({
  required bool reduceTransparency,
  required bool isWeb,
}) => RustLib.instance.api.crateApiGlassResolveTier(
  reduceTransparency: reduceTransparency,
  isWeb: isWeb,
);

/// 感知交互行为 — the bloom that answers a touch.
String touchLightColor({required bool isDark}) =>
    RustLib.instance.api.crateApiGlassTouchLightColor(isDark: isDark);

/// Relative luminance, exposed because the UI decides content density from it.
double luminance({required String hex}) =>
    RustLib.instance.api.crateApiGlassLuminance(hex: hex);

/// The 4x5 colour matrix a renderer applies to the blurred backdrop.
///
/// Twenty numbers rather than one, because the matrix is what every platform's
/// API actually takes and deriving it in each renderer is exactly the kind of
/// arithmetic this crate exists to hold on one side of the boundary.
Float64List saturationMatrix({required double vibrancy}) =>
    RustLib.instance.api.crateApiGlassSaturationMatrix(vibrancy: vibrancy);

ScrimSpec scrimSpec({required bool isDark, required GlassTier tier}) =>
    RustLib.instance.api.crateApiGlassScrimSpec(isDark: isDark, tier: tier);

/// The ramp, as the stack of nested blurs a renderer can actually draw.
///
/// The per-band sigma is not `sigma / bands`: blurs compose by variance, so
/// looking through σ=3 and then σ=4 is looking through σ=5. Getting that wrong
/// puts the whole ramp in the top two bands, which is the opposite of the
/// effect. `core::glass` states the curve; this hands over the steps.
List<ScrimBand> scrimBands({required double sigma, required int bands}) =>
    RustLib.instance.api.crateApiGlassScrimBands(sigma: sigma, bands: bands);

/// The wash's alpha at each band edge, `bands + 1` of them.
Float64List scrimRamp({required double wash, required int bands}) =>
    RustLib.instance.api.crateApiGlassScrimRamp(wash: wash, bands: bands);

/// Where a glass surface sits in the stack.
enum GlassLevel { chrome, sheet, card }

/// The per-level constants, as Dart can hold them. `edge` widens from
/// `&'static str` to `String` because a borrowed lifetime cannot cross.
class GlassSpec {
  final double intensity;
  final double washAlpha;
  final double washAlphaFlat;
  final double sheen;
  final double sheenHeight;
  final String edge;

  /// Negative means "the platform's hairline" — Flutter substitutes
  /// `1 / devicePixelRatio`, the way `StyleSheet.hairlineWidth` did.
  final double edgeWidth;

  /// Saturation applied to the blurred backdrop. See `core::glass`.
  final double vibrancy;

  /// The lit rim, top and bottom.
  final double rimTop;
  final double rimBottom;

  /// Grain, to break the banding a wide blur leaves behind.
  final double noise;

  const GlassSpec({
    required this.intensity,
    required this.washAlpha,
    required this.washAlphaFlat,
    required this.sheen,
    required this.sheenHeight,
    required this.edge,
    required this.edgeWidth,
    required this.vibrancy,
    required this.rimTop,
    required this.rimBottom,
    required this.noise,
  });

  @override
  int get hashCode =>
      intensity.hashCode ^
      washAlpha.hashCode ^
      washAlphaFlat.hashCode ^
      sheen.hashCode ^
      sheenHeight.hashCode ^
      edge.hashCode ^
      edgeWidth.hashCode ^
      vibrancy.hashCode ^
      rimTop.hashCode ^
      rimBottom.hashCode ^
      noise.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlassSpec &&
          runtimeType == other.runtimeType &&
          intensity == other.intensity &&
          washAlpha == other.washAlpha &&
          washAlphaFlat == other.washAlphaFlat &&
          sheen == other.sheen &&
          sheenHeight == other.sheenHeight &&
          edge == other.edge &&
          edgeWidth == other.edgeWidth &&
          vibrancy == other.vibrancy &&
          rimTop == other.rimTop &&
          rimBottom == other.rimBottom &&
          noise == other.noise;
}

/// How much of the material a device can actually render.
enum GlassTier { full, wash, solid }

/// One step of the ramp.
class ScrimBand {
  /// The band's top edge, 0 at the top of the scrim and 1 at the bottom.
  final double top;

  /// Where the band's mask reaches full strength; it fades in from nothing
  /// at `top`, which is what keeps the joins from showing.
  final double full;

  /// The sigma this band contributes, not the blur seen through it.
  final double sigma;

  const ScrimBand({required this.top, required this.full, required this.sigma});

  @override
  int get hashCode => top.hashCode ^ full.hashCode ^ sigma.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScrimBand &&
          runtimeType == other.runtimeType &&
          top == other.top &&
          full == other.full &&
          sigma == other.sigma;
}

/// 渐进模糊 — how the ground under a floating surface dissolves.
class ScrimSpec {
  /// How far the fade reaches beyond the surface, in dp. The renderer adds
  /// the surface's own height and the gesture inset.
  final double fade;

  /// How much of a header's own height the ramp takes, from its bottom
  /// edge up. Inside the header, unlike `fade`.
  final double headerRamp;

  /// Blur sigma at the deepest point; zero below the `Full` tier.
  final double sigma;
  final int bands;

  /// Alpha of the paper wash at the deepest point.
  final double wash;

  const ScrimSpec({
    required this.fade,
    required this.headerRamp,
    required this.sigma,
    required this.bands,
    required this.wash,
  });

  @override
  int get hashCode =>
      fade.hashCode ^
      headerRamp.hashCode ^
      sigma.hashCode ^
      bands.hashCode ^
      wash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScrimSpec &&
          runtimeType == other.runtimeType &&
          fade == other.fade &&
          headerRamp == other.headerRamp &&
          sigma == other.sigma &&
          bands == other.bands &&
          wash == other.wash;
}
