// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_day`

/// How many days in a row end today, counting back.
///
/// `days` is one `y-m-d` per entry, resolved by Dart. Duplicates and order do
/// not matter — the core folds them into a set of distinct days before
/// counting.
int streak({required List<String> days, required String today}) =>
    RustLib.instance.api.crateApiHistoryStreak(days: days, today: today);

/// The notes this category is usually given, most-used first.
///
/// Offered rather than imposed: the record sheet shows these as chips, and a
/// user who wants something else types it. An empty list is the ordinary state
/// for a category used for the first time, not a failure.
List<String> noteHints({
  required String io,
  required String cat,
  required int limit,
}) => RustLib.instance.api.crateApiHistoryNoteHints(
  io: io,
  cat: cat,
  limit: limit,
);
