// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'report.dart';

// These functions are ignored because they are not marked as `pub`: `parse_day`, `pot`, `show_day`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// 明细's head, for the cycle `today` is in.
///
/// `ids` and `days_of` are every live entry and the local day Dart resolved
/// for each; the cycle is chosen here, from the setting, so the head and 统计
/// cannot disagree about where this month began.
HomeView home({
  required List<String> ids,
  required List<String> daysOf,
  required String today,
  required bool zh,
  required InsightCopyView copy,
}) => RustLib.instance.api.crateApiHomeHome(
  ids: ids,
  daysOf: daysOf,
  today: today,
  zh: zh,
  copy: copy,
);

/// The head of 明细.
class HomeView {
  /// The current accounting cycle, `y-m-d`.
  final String start;
  final String last;
  final double exp;
  final double inc;

  /// Income less expense — 本月攒下的.
  final double net;

  /// Spending's share of what moved, for the bar; `None` when nothing did.
  final double? expShare;

  /// The cycle's pot and today's, each `None` when its cap is not set.
  final PotView? monthly;
  final PotView? daily;

  /// `fresh`, `wary` or `wilted` — the flower beside the pots, following the
  /// cycle's pot when there is one. `None` when no cap is set.
  final String? mood;
  final InsightView? insight;

  const HomeView({
    required this.start,
    required this.last,
    required this.exp,
    required this.inc,
    required this.net,
    this.expShare,
    this.monthly,
    this.daily,
    this.mood,
    this.insight,
  });

  @override
  int get hashCode =>
      start.hashCode ^
      last.hashCode ^
      exp.hashCode ^
      inc.hashCode ^
      net.hashCode ^
      expShare.hashCode ^
      monthly.hashCode ^
      daily.hashCode ^
      mood.hashCode ^
      insight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomeView &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          last == other.last &&
          exp == other.exp &&
          inc == other.inc &&
          net == other.net &&
          expShare == other.expShare &&
          monthly == other.monthly &&
          daily == other.daily &&
          mood == other.mood &&
          insight == other.insight;
}

/// One of the two budget pots.
class PotView {
  final double limit;
  final double used;

  /// Negative once over.
  final double left;
  final bool over;

  /// The bar, 0..1 — full once over.
  final double fill;

  const PotView({
    required this.limit,
    required this.used,
    required this.left,
    required this.over,
    required this.fill,
  });

  @override
  int get hashCode =>
      limit.hashCode ^
      used.hashCode ^
      left.hashCode ^
      over.hashCode ^
      fill.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PotView &&
          runtimeType == other.runtimeType &&
          limit == other.limit &&
          used == other.used &&
          left == other.left &&
          over == other.over &&
          fill == other.fill;
}
