// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_day`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

/// Read a picked file and work out what importing it would do.
///
/// Nothing is written. `ids` and `days_of` are the live ledger in its own
/// order, so dedup sees the entries as they are at the moment of the pick
/// rather than as they were when the screen opened.
///
/// Custom categories are passed empty: this port has no custom-category
/// editor, so there are none to pass. When it gains one, they go here — the
/// core already takes them, and `map_category` prefers a custom keyword match
/// over a built-in one.
ImportPreview previewBills({
  required List<int> bytes,
  required List<String> ids,
  required List<String> daysOf,
}) => RustLib.instance.api.crateApiImportsPreviewBills(
  bytes: bytes,
  ids: ids,
  daysOf: daysOf,
);

/// One row the import would add, or has recognised as already present.
class CandidateView {
  final String io;
  final String cat;
  final double amt;
  final String note;

  /// The wall-clock time the file gave, for Dart to turn into an instant.
  /// `mo` is 1-based, matching `DateTime`, not the core's 0-based month.
  final int y;
  final int mo;
  final int d;
  final int h;
  final int mi;
  final int s;

  /// The ledger already holds this one.
  final bool dup;

  const CandidateView({
    required this.io,
    required this.cat,
    required this.amt,
    required this.note,
    required this.y,
    required this.mo,
    required this.d,
    required this.h,
    required this.mi,
    required this.s,
    required this.dup,
  });

  @override
  int get hashCode =>
      io.hashCode ^
      cat.hashCode ^
      amt.hashCode ^
      note.hashCode ^
      y.hashCode ^
      mo.hashCode ^
      d.hashCode ^
      h.hashCode ^
      mi.hashCode ^
      s.hashCode ^
      dup.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CandidateView &&
          runtimeType == other.runtimeType &&
          io == other.io &&
          cat == other.cat &&
          amt == other.amt &&
          note == other.note &&
          y == other.y &&
          mo == other.mo &&
          d == other.d &&
          h == other.h &&
          mi == other.mi &&
          s == other.s &&
          dup == other.dup;
}

/// Everything the import screen shows before anything is written.
class ImportPreview {
  /// `alipay`, `wechat` or `generic`.
  final String source;

  /// A header was found and at least one row came out of it. False means the
  /// file is not a bill export this app understands, and the screen says so
  /// rather than showing an empty list that looks like an empty file.
  final bool ok;

  /// Every candidate, duplicates included, in file order. The screen shows
  /// them all — a row the import will skip is information, not noise.
  final List<CandidateView> candidates;
  final int freshCount;
  final int dupCount;

  /// Data rows below the header that could not be read at all.
  final int skipped;
  final List<RowErrorView> errors;
  final int expCount;
  final int incCount;
  final double expSum;
  final double incSum;

  const ImportPreview({
    required this.source,
    required this.ok,
    required this.candidates,
    required this.freshCount,
    required this.dupCount,
    required this.skipped,
    required this.errors,
    required this.expCount,
    required this.incCount,
    required this.expSum,
    required this.incSum,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      ok.hashCode ^
      candidates.hashCode ^
      freshCount.hashCode ^
      dupCount.hashCode ^
      skipped.hashCode ^
      errors.hashCode ^
      expCount.hashCode ^
      incCount.hashCode ^
      expSum.hashCode ^
      incSum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportPreview &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          ok == other.ok &&
          candidates == other.candidates &&
          freshCount == other.freshCount &&
          dupCount == other.dupCount &&
          skipped == other.skipped &&
          errors == other.errors &&
          expCount == other.expCount &&
          incCount == other.incCount &&
          expSum == other.expSum &&
          incSum == other.incSum;
}

class RowErrorView {
  /// 1-indexed line in the original file.
  final int row;
  final String reason;

  const RowErrorView({required this.row, required this.reason});

  @override
  int get hashCode => row.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RowErrorView &&
          runtimeType == other.runtimeType &&
          row == other.row &&
          reason == other.reason;
}
