// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `spec`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

LiquidSpec liquidSpec({required bool isDark}) =>
    RustLib.instance.api.crateApiLiquidLiquidSpec(isDark: isDark);

/// The lens's shape at `velocity` dp/s.
Lens lens({required bool isDark, required double velocity}) =>
    RustLib.instance.api.crateApiLiquidLens(isDark: isDark, velocity: velocity);

/// Which tab sits under `x`, measured from the row's left edge. Live, while a
/// finger is dragging.
int tabAt({required double x, required double itemW, required int count}) =>
    RustLib.instance.api.crateApiLiquidTabAt(x: x, itemW: itemW, count: count);

/// Where a tab's lens rests.
double centreOf({required int index, required double itemW}) =>
    RustLib.instance.api.crateApiLiquidCentreOf(index: index, itemW: itemW);

/// Which tab a release at `x` moving at `velocity` lands on — the tab it was
/// heading for, not the nearest one.
int snap({
  required bool isDark,
  required double x,
  required double itemW,
  required int count,
  required double velocity,
}) => RustLib.instance.api.crateApiLiquidSnap(
  isDark: isDark,
  x: x,
  itemW: itemW,
  count: count,
  velocity: velocity,
);

/// What the lens looks like at one velocity.
class Lens {
  /// Wider than 1 in the direction of travel.
  final double scaleX;

  /// And thinner by the reciprocal, so the area does not change.
  final double scaleY;

  /// Where the shadow sits, in dp, signed against the travel.
  final double trail;

  /// The highlight across the lens, 0..1.
  final double sheenAt;

  const Lens({
    required this.scaleX,
    required this.scaleY,
    required this.trail,
    required this.sheenAt,
  });

  @override
  int get hashCode =>
      scaleX.hashCode ^ scaleY.hashCode ^ trail.hashCode ^ sheenAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Lens &&
          runtimeType == other.runtimeType &&
          scaleX == other.scaleX &&
          scaleY == other.scaleY &&
          trail == other.trail &&
          sheenAt == other.sheenAt;
}

/// The constants a moving lens is made of. Distances dp, velocities dp/s.
class LiquidSpec {
  /// The settle spring, as a renderer's spring description takes it.
  final double mass;
  final double stiffness;
  final double damping;
  final double stretch;
  final double stretchMax;
  final double trail;
  final double trailMax;
  final double fling;
  final double sheenTravel;
  final double topSpeed;

  /// The drop shadow: how dark, how soft, how far below at rest.
  final double shadowAlpha;
  final double shadowBlur;
  final double shadowLift;

  const LiquidSpec({
    required this.mass,
    required this.stiffness,
    required this.damping,
    required this.stretch,
    required this.stretchMax,
    required this.trail,
    required this.trailMax,
    required this.fling,
    required this.sheenTravel,
    required this.topSpeed,
    required this.shadowAlpha,
    required this.shadowBlur,
    required this.shadowLift,
  });

  @override
  int get hashCode =>
      mass.hashCode ^
      stiffness.hashCode ^
      damping.hashCode ^
      stretch.hashCode ^
      stretchMax.hashCode ^
      trail.hashCode ^
      trailMax.hashCode ^
      fling.hashCode ^
      sheenTravel.hashCode ^
      topSpeed.hashCode ^
      shadowAlpha.hashCode ^
      shadowBlur.hashCode ^
      shadowLift.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiquidSpec &&
          runtimeType == other.runtimeType &&
          mass == other.mass &&
          stiffness == other.stiffness &&
          damping == other.damping &&
          stretch == other.stretch &&
          stretchMax == other.stretchMax &&
          trail == other.trail &&
          trailMax == other.trailMax &&
          fling == other.fling &&
          sheenTravel == other.sheenTravel &&
          topSpeed == other.topSpeed &&
          shadowAlpha == other.shadowAlpha &&
          shadowBlur == other.shadowBlur &&
          shadowLift == other.shadowLift;
}
