// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lock`, `out`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

/// The gate appeared.
List<LockAction> lockMounted() =>
    RustLib.instance.api.crateApiLockLockMounted();

/// The setting was turned on or off.
List<LockAction> lockSetEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiLockLockSetEnabled(enabled: enabled);

/// The app came back to the foreground.
List<LockAction> lockResumed() =>
    RustLib.instance.api.crateApiLockLockResumed();

/// The app really left. Distinct from [`lock_inactive`], and the difference
/// decides whether a prompt still up is worth superseding.
List<LockAction> lockBackgrounded() =>
    RustLib.instance.api.crateApiLockLockBackgrounded();

/// The app is briefly not frontmost — which is what the system's own auth
/// dialog looks like from here.
List<LockAction> lockInactive() =>
    RustLib.instance.api.crateApiLockLockInactive();

/// The user pressed the button on the gate.
List<LockAction> lockUnlockPressed() =>
    RustLib.instance.api.crateApiLockLockUnlockPressed();

/// What the device can do. Carry back the `attempt` from the `runAuth`.
List<LockAction> lockCapability({
  required BigInt attempt,
  required bool hasHardware,
  required bool enrolled,
}) => RustLib.instance.api.crateApiLockLockCapability(
  attempt: attempt,
  hasHardware: hasHardware,
  enrolled: enrolled,
);

/// How the prompt ended. `outcome` is `success`, `rejected` or `errored`.
///
/// The three are not interchangeable: a rejection is a wrong finger and a
/// retry may work, while an error means the question could not be asked.
List<LockAction> lockSettled({
  required BigInt attempt,
  required String outcome,
}) => RustLib.instance.api.crateApiLockLockSettled(
  attempt: attempt,
  outcome: outcome,
);

/// Whether the app's content should be covered right now.
bool lockGated() => RustLib.instance.api.crateApiLockLockGated();

/// Whether the setting is on.
bool lockEnabled() => RustLib.instance.api.crateApiLockLockEnabled();

/// What the gate is saying, if anything.
String? lockNotice() => RustLib.instance.api.crateApiLockLockNotice();

/// Restore the setting from the config, without prompting.
///
/// Separate from [`lock_set_enabled`] on purpose: loading a config is not a
/// user turning the lock on, and prompting during a file read would ask before
/// there is a screen to ask on top of.
void lockLoad({required bool enabled}) =>
    RustLib.instance.api.crateApiLockLockLoad(enabled: enabled);

/// Forget everything. For tests, which share one process.
void lockReset() => RustLib.instance.api.crateApiLockLockReset();

/// One thing for the platform to do.
class LockAction {
  /// `runAuth`, `cancelAuth`, `unlock`, `relock` or `notice`.
  final String kind;

  /// Which attempt a `runAuth` belongs to. Every answer must carry it back,
  /// or the core cannot tell a live prompt from an abandoned one.
  final BigInt attempt;

  /// For `notice`: `failed`, `unavailable`, or absent to stop saying
  /// anything.
  final String? notice;

  const LockAction({required this.kind, required this.attempt, this.notice});

  @override
  int get hashCode => kind.hashCode ^ attempt.hashCode ^ notice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LockAction &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          attempt == other.attempt &&
          notice == other.notice;
}
