// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A bare amount with grouping and two decimals: `12,345.68`.
String fmtNum({required double n}) =>
    RustLib.instance.api.crateApiMoneyFmtNum(n: n);

/// An amount with its currency symbol in front: `￥12,345.68`.
String fmt({required double n, required String symbol}) =>
    RustLib.instance.api.crateApiMoneyFmt(n: n, symbol: symbol);

/// An abbreviated amount for a tight space: `￥1.2万`, `￥1.2k`.
String fmtShort({required double n, required String symbol}) =>
    RustLib.instance.api.crateApiMoneyFmtShort(n: n, symbol: symbol);

/// The symbol for a currency code, or the code itself when there is none.
String curSymbol({required String code}) =>
    RustLib.instance.api.crateApiMoneyCurSymbol(code: code);

/// A signed amount as the entry list writes it: `-35.50`, `+9,000.00`.
///
/// The sign follows the direction rather than the number, so a negative
/// expense — which a refund adjustment can produce — still reads as an expense.
/// That is what the shipping list does: `d.io === 'exp' ? '-' : '+'`, then the
/// magnitude formatted separately.
String fmtSigned({required double n, required String io}) =>
    RustLib.instance.api.crateApiMoneyFmtSigned(n: n, io: io);

/// `String(n)` from JavaScript — what a number looks like when it is put into
/// a text field rather than shown as money.
///
/// Not `fmt_num`: that groups and pads to two decimals, and a keypad
/// expression of `35.50` would read back as a different number from the `35.5`
/// the template holds. JavaScript switches to exponent notation at 1e21 and
/// 1e-7, and this is where that switch has to be the same on both sides.
String plain({required double n}) =>
    RustLib.instance.api.crateApiMoneyPlain(n: n);
