// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `assets_lock`, `assets_of`, `loans_lock`, `loans_of`, `set_assets_inner`, `set_loans_inner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`

List<AssetView> assets() => RustLib.instance.api.crateApiNetworthAssets();

String addAsset({
  required String id,
  required String name,
  required String kind,
  required double val,
}) => RustLib.instance.api.crateApiNetworthAddAsset(
  id: id,
  name: name,
  kind: kind,
  val: val,
);

void removeAsset({required String id}) =>
    RustLib.instance.api.crateApiNetworthRemoveAsset(id: id);

/// Keep an asset on the list but out of the total.
///
/// The flag is stored either way rather than omitted when false — see the
/// module docs.
bool setAssetNoCount({required String id, required bool noCount}) => RustLib
    .instance
    .api
    .crateApiNetworthSetAssetNoCount(id: id, noCount: noCount);

List<LoanView> loans() => RustLib.instance.api.crateApiNetworthLoans();

/// Create a loan. `ts` is the caller's, because the TypeScript reads
/// `Date.now()` there and clocks stay outside the core.
String addLoan({
  required String id,
  required String who,
  required String kind,
  required double amt,
  required PlatformInt64 ts,
}) => RustLib.instance.api.crateApiNetworthAddLoan(
  id: id,
  who: who,
  kind: kind,
  amt: amt,
  ts: ts,
);

/// Record a repayment, capped at what is still owed.
///
/// The cap is **one-sided**, exactly as in the TypeScript: `Math.min(amount,
/// remaining)` stops an overpayment but does nothing about a negative amount,
/// which walks the counter back down. That is how a mis-tap is undone, so it is
/// left reachable rather than validated away here.
void repayLoan({required String id, required double amount}) =>
    RustLib.instance.api.crateApiNetworthRepayLoan(id: id, amount: amount);

void removeLoan({required String id}) =>
    RustLib.instance.api.crateApiNetworthRemoveLoan(id: id);

NetWorthView netWorth() => RustLib.instance.api.crateApiNetworthNetWorth();

/// Something owned or owed that is not an account — a flat, a car, a mortgage.
class AssetView {
  final String id;
  final String name;

  /// `asset` | `liab`.
  final String kind;
  final double val;

  /// Left out of the net-worth total, without being deleted.
  final bool noCount;

  const AssetView({
    required this.id,
    required this.name,
    required this.kind,
    required this.val,
    required this.noCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      kind.hashCode ^
      val.hashCode ^
      noCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssetView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          kind == other.kind &&
          val == other.val &&
          noCount == other.noCount;
}

/// Money lent to someone, or borrowed from them.
class LoanView {
  final String id;
  final String who;

  /// `lend` — they owe me — or `borrow`.
  final String kind;
  final double amt;
  final double repaid;

  /// `amt - repaid`, never negative. A `NaN` amount stays `NaN` rather than
  /// reading as settled.
  final double remaining;
  final PlatformInt64 ts;

  const LoanView({
    required this.id,
    required this.who,
    required this.kind,
    required this.amt,
    required this.repaid,
    required this.remaining,
    required this.ts,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      who.hashCode ^
      kind.hashCode ^
      amt.hashCode ^
      repaid.hashCode ^
      remaining.hashCode ^
      ts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoanView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          who == other.who &&
          kind == other.kind &&
          amt == other.amt &&
          repaid == other.repaid &&
          remaining == other.remaining &&
          ts == other.ts;
}

/// What the two cards on the net-worth screen show.
class NetWorthView {
  final double asset;
  final double liab;

  /// The difference, and the sum of every balance either way.
  final double net;

  const NetWorthView({
    required this.asset,
    required this.liab,
    required this.net,
  });

  @override
  int get hashCode => asset.hashCode ^ liab.hashCode ^ net.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetWorthView &&
          runtimeType == other.runtimeType &&
          asset == other.asset &&
          liab == other.liab &&
          net == other.net;
}
