// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_day`, `period_of`, `show_day`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

/// The window of `period` containing `anchor`.
///
/// The cycle start comes from the store rather than the caller: it is a setting
/// the user has already made, and a screen passing its own would be a second
/// place for it to be wrong.
WindowView periodWindow({required String anchor, required String period}) =>
    RustLib.instance.api.crateApiPeriodPeriodWindow(
      anchor: anchor,
      period: period,
    );

/// Move the anchor by whole periods. Negative goes earlier.
String stepPeriod({
  required String anchor,
  required String period,
  required int dir,
}) => RustLib.instance.api.crateApiPeriodStepPeriod(
  anchor: anchor,
  period: period,
  dir: dir,
);

/// Which of `ids` fall inside the window, in the order given.
///
/// `days_of` is each entry's local calendar day, as everywhere else — the
/// comparison is between calendar days rather than instants, so an entry at
/// 23:50 belongs to the day the phone showed it on.
List<String> idsInPeriod({
  required List<String> ids,
  required List<String> daysOf,
  required String anchor,
  required String period,
}) => RustLib.instance.api.crateApiPeriodIdsInPeriod(
  ids: ids,
  daysOf: daysOf,
  anchor: anchor,
  period: period,
);

/// One window. Half-open, as the core builds it: `start` is in, `end` is not.
class WindowView {
  final String start;

  /// The first day **after** the window.
  final String end;

  /// The last day in it, which is what a screen shows and what a trend
  /// counting backwards has to start from.
  final String last;

  /// How many days long, so a daily trend can cover exactly the window.
  final int days;

  const WindowView({
    required this.start,
    required this.end,
    required this.last,
    required this.days,
  });

  @override
  int get hashCode =>
      start.hashCode ^ end.hashCode ^ last.hashCode ^ days.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WindowView &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          last == other.last &&
          days == other.days;
}
