// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_day`, `source_str`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

/// Whether a date is close enough to now to bother asking the live-only source.
///
/// `now_minutes` is minutes past local midnight, which is how the platform
/// hands over the part of the clock that matters. Deliberately not "today or
/// yesterday": the shipping app measures 48 hours from the current instant, so
/// the window slides through the day and reaches into the future. Reproduced
/// rather than corrected — the worst a generous window costs is one request
/// that returns nothing useful.
bool rateDateIsRecent({
  required String date,
  required String today,
  required PlatformInt64 nowMinutes,
}) => RustLib.instance.api.crateApiRatesRateDateIsRecent(
  date: date,
  today: today,
  nowMinutes: nowMinutes,
);

/// Turn one API answer into this app's convention, or reject it.
///
/// Exposed on its own so a caller can see what a single source was worth. A
/// zero, a negative, an infinity and a `NaN` are all refused rather than
/// producing a nonsensical rate.
double? invertRate({double? raw}) =>
    RustLib.instance.api.crateApiRatesInvertRate(raw: raw);

/// Pick a rate from what the three sources said.
///
/// `historical` and `live` are raw API numbers, still in "1 base = X target".
/// `cached` is what the store holds and is already in this app's convention, so
/// it is not inverted.
ResolvedRate resolveRate({
  required bool sameCurrency,
  double? historical,
  required bool liveAllowed,
  double? live,
  double? cached,
}) => RustLib.instance.api.crateApiRatesResolveRate(
  sameCurrency: sameCurrency,
  historical: historical,
  liveAllowed: liveAllowed,
  live: live,
  cached: cached,
);

/// Where a rate came from, and what it is.
class ResolvedRate {
  /// Absent when nothing usable was found anywhere.
  final double? rate;

  /// `identity`, `historical`, `live`, `cache` or `none` — worth surfacing,
  /// because a rate from the cache is a different claim from a rate fetched
  /// for the entry's own date.
  final String source;

  const ResolvedRate({this.rate, required this.source});

  @override
  int get hashCode => rate.hashCode ^ source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResolvedRate &&
          runtimeType == other.runtimeType &&
          rate == other.rate &&
          source == other.source;
}
