// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`, `from`

/// Why a form cannot be saved: `"amount"`, `"xferTo"`, `"xferSame"`, or
/// `"noRate:USD"`. `None` means it can.
///
/// A tagged string rather than a Dart enum with a payload, because only one
/// rejection carries anything and a `switch` on a prefix is less machinery than
/// a sealed class for it.
String? validateForm({required FormView form}) =>
    RustLib.instance.api.crateApiRecordValidateForm(form: form);

/// Validate, shape and write, in one call.
///
/// Deliberately one call: the TypeScript's `save()` split validation from
/// writing and had a path where the write happened and the caller was told
/// something that read like a failure. Here a caller cannot write without
/// validating, and cannot be told "rejected" about a row that exists.
///
/// `edit_id` empty means a new entry. `rate_override` is a rate fetched for the
/// entry's own date, which the platform's HTTP goes and gets.
SaveResult saveForm({
  required FormView form,
  required String editId,
  required String id,
  required PlatformInt64 now,
  double? rateOverride,
  required bool rateWasCached,
}) => RustLib.instance.api.crateApiRecordSaveForm(
  form: form,
  editId: editId,
  id: id,
  now: now,
  rateOverride: rateOverride,
  rateWasCached: rateWasCached,
);

/// Whether a fetched rate is really the cached one, within a tolerance.
///
/// The tolerance is the point: the same rate from the network and from storage
/// has been through a JSON round trip, and is not obliged to come back as the
/// same double.
bool rateIsCached({double? fetched, double? cached}) => RustLib.instance.api
    .crateApiRecordRateIsCached(fetched: fetched, cached: cached);

/// The cached rate for a code, which the platform's fetcher compares against.
double? cachedRate({required String code}) =>
    RustLib.instance.api.crateApiRecordCachedRate(code: code);

/// The fields a sheet opens with.
///
/// `source_id` empty means a fresh entry. `editing` distinguishes an edit from
/// a duplicate, and the difference is one field: a duplicate keeps the source's
/// values but not its date, so 再记一笔 lands today.
FormView initialForm({
  required String sourceId,
  required bool editing,
  PlatformInt64? initialTs,
  required String ledger,
}) => RustLib.instance.api.crateApiRecordInitialForm(
  sourceId: sourceId,
  editing: editing,
  initialTs: initialTs,
  ledger: ledger,
);

/// What changes when a direction is picked.
///
/// The visible accounts come from the store rather than from Dart: a transfer
/// needs a *second* account, and which accounts exist is state this side owns.
FormView pickDirection({required String next, required FormView form}) =>
    RustLib.instance.api.crateApiRecordPickDirection(next: next, form: form);

/// What clears after 再记, so the next entry of the same kind can be typed.
FormView clearForNext({required FormView form}) =>
    RustLib.instance.api.crateApiRecordClearForNext(form: form);

/// The currency settings the record sheet's decisions read.
///
/// Held here rather than in Dart for the same reason the ledger is: two copies
/// of one table is one too many, and `validate` refuses a save on this.
void setCurrencies({
  required String base,
  required List<String> codes,
  required List<double> rates,
}) => RustLib.instance.api.crateApiRecordSetCurrencies(
  base: base,
  codes: codes,
  rates: rates,
);

String baseCurrency() => RustLib.instance.api.crateApiRecordBaseCurrency();

/// The record sheet's fields, as Dart holds them.
///
/// Strings where the user types strings — `amt` is a calculator *expression*,
/// not a number, and `fee` is free text whose leading number is what counts.
class FormView {
  final String io;
  final String cat;
  final String amt;
  final String note;
  final String acct;
  final String acctTo;
  final String fee;
  final String discount;
  final List<String> tags;
  final String ledger;
  final String cur;
  final String subcat;

  /// When it happened. `None` is "now", resolved at save time.
  final PlatformInt64? ts;

  const FormView({
    required this.io,
    required this.cat,
    required this.amt,
    required this.note,
    required this.acct,
    required this.acctTo,
    required this.fee,
    required this.discount,
    required this.tags,
    required this.ledger,
    required this.cur,
    required this.subcat,
    this.ts,
  });

  static Future<FormView> default_() =>
      RustLib.instance.api.crateApiRecordFormViewDefault();

  @override
  int get hashCode =>
      io.hashCode ^
      cat.hashCode ^
      amt.hashCode ^
      note.hashCode ^
      acct.hashCode ^
      acctTo.hashCode ^
      fee.hashCode ^
      discount.hashCode ^
      tags.hashCode ^
      ledger.hashCode ^
      cur.hashCode ^
      subcat.hashCode ^
      ts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FormView &&
          runtimeType == other.runtimeType &&
          io == other.io &&
          cat == other.cat &&
          amt == other.amt &&
          note == other.note &&
          acct == other.acct &&
          acctTo == other.acctTo &&
          fee == other.fee &&
          discount == other.discount &&
          tags == other.tags &&
          ledger == other.ledger &&
          cur == other.cur &&
          subcat == other.subcat &&
          ts == other.ts;
}

/// What a save did.
class SaveResult {
  /// The rejection kind, when the form could not be saved.
  final String? rejected;

  /// The id written, when it could.
  final String? id;

  /// True when a stale cached rate was used — a notice about a **saved**
  /// entry, not a failure. Keeping the two apart is what stopped the
  /// TypeScript from writing the entry twice.
  final bool staleRate;

  const SaveResult({this.rejected, this.id, required this.staleRate});

  @override
  int get hashCode => rejected.hashCode ^ id.hashCode ^ staleRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SaveResult &&
          runtimeType == other.runtimeType &&
          rejected == other.rejected &&
          id == other.id &&
          staleRate == other.staleRate;
}
