// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

ClaimList claims({required bool zh}) =>
    RustLib.instance.api.crateApiReimburseClaims(zh: zh);

/// Cycle the claim state: nothing → pending → (confirm) done → pending.
///
/// Only `pending` clears. A settled claim re-opens rather than disappearing.
bool toggleReimburse({required String id, required PlatformInt64 now}) =>
    RustLib.instance.api.crateApiReimburseToggleReimburse(id: id, now: now);

/// Settle a claim, recording what came back.
bool confirmReimburse({required String id, required PlatformInt64 now}) =>
    RustLib.instance.api.crateApiReimburseConfirmReimburse(id: id, now: now);

/// Drop the claim entirely, state and amount together.
bool unmarkReimburse({required String id, required PlatformInt64 now}) =>
    RustLib.instance.api.crateApiReimburseUnmarkReimburse(id: id, now: now);

/// Refund part or all of an expense. Returns how much was actually refunded.
///
/// Zero for an unknown id, for one already fully refunded, or for an amount
/// that is not positive — the cap is the core's, and a screen that clamped
/// first would be a second implementation of it.
double refundEntry({
  required String id,
  required double amount,
  required bool zh,
  required String newId,
  required PlatformInt64 now,
}) => RustLib.instance.api.crateApiReimburseRefundEntry(
  id: id,
  amount: amount,
  zh: zh,
  newId: newId,
  now: now,
);

RefundState? refundState({required String id}) =>
    RustLib.instance.api.crateApiReimburseRefundState(id: id);

/// Everything the screen needs, in one pass over the ledger.
class ClaimList {
  /// Newest first, pending and settled together — the shipping screen sorts
  /// by date rather than grouping by state, so a claim does not jump when it
  /// is settled.
  final List<ClaimView> items;

  /// Outstanding: the sum of the pending amounts.
  final double pendingSum;

  /// Settled: the sum of what came back, not of what was spent.
  final double doneSum;

  const ClaimList({
    required this.items,
    required this.pendingSum,
    required this.doneSum,
  });

  static Future<ClaimList> default_() =>
      RustLib.instance.api.crateApiReimburseClaimListDefault();

  @override
  int get hashCode => items.hashCode ^ pendingSum.hashCode ^ doneSum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClaimList &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          pendingSum == other.pendingSum &&
          doneSum == other.doneSum;
}

/// One claim, as the screen draws it.
class ClaimView {
  final String id;

  /// `pending` | `done`.
  final String state;
  final String cat;
  final String name;
  final String emoji;

  /// `#RRGGBB`.
  final String color;
  final String note;
  final double amt;

  /// What was actually reimbursed. Falls back to the amount for a settled
  /// claim that predates the field.
  final double rbAmt;
  final PlatformInt64 ts;

  const ClaimView({
    required this.id,
    required this.state,
    required this.cat,
    required this.name,
    required this.emoji,
    required this.color,
    required this.note,
    required this.amt,
    required this.rbAmt,
    required this.ts,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      state.hashCode ^
      cat.hashCode ^
      name.hashCode ^
      emoji.hashCode ^
      color.hashCode ^
      note.hashCode ^
      amt.hashCode ^
      rbAmt.hashCode ^
      ts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClaimView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          state == other.state &&
          cat == other.cat &&
          name == other.name &&
          emoji == other.emoji &&
          color == other.color &&
          note == other.note &&
          amt == other.amt &&
          rbAmt == other.rbAmt &&
          ts == other.ts;
}

/// How much of an expense has already come back, and how much still could.
class RefundState {
  final double refunded;

  /// `amt - refunded`, never negative.
  final double remaining;

  const RefundState({required this.refunded, required this.remaining});

  @override
  int get hashCode => refunded.hashCode ^ remaining.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RefundState &&
          runtimeType == other.runtimeType &&
          refunded == other.refunded &&
          remaining == other.remaining;
}
