// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `settings`, `view`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Prefs`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// Every reminder that is on, with when it fires. Empty when none are.
List<ScheduleView> activeSchedules() =>
    RustLib.instance.api.crateApiRemindActiveSchedules();

/// Every id this app ever schedules under.
///
/// The platform cancels these by id rather than cancelling everything: an app
/// is not the only thing that may have posted a notification, and "cancel all"
/// is a claim over other people's work.
Int32List allIds() => RustLib.instance.api.crateApiRemindAllIds();

/// Set the daily reminder's time. An empty or unparseable string turns it off.
bool setDailyReminder({required String at}) =>
    RustLib.instance.api.crateApiRemindSetDailyReminder(at: at);

String dailyReminderAt() =>
    RustLib.instance.api.crateApiRemindDailyReminderAt();

void setWeeklyReport({required bool enabled}) =>
    RustLib.instance.api.crateApiRemindSetWeeklyReport(enabled: enabled);

void setMonthlyReport({required bool enabled}) =>
    RustLib.instance.api.crateApiRemindSetMonthlyReport(enabled: enabled);

bool weeklyReportOn() => RustLib.instance.api.crateApiRemindWeeklyReportOn();

bool monthlyReportOn() => RustLib.instance.api.crateApiRemindMonthlyReportOn();

/// Restore from the config, without scheduling anything.
void loadReminders({
  required String dailyAt,
  required bool weekly,
  required bool monthly,
}) => RustLib.instance.api.crateApiRemindLoadReminders(
  dailyAt: dailyAt,
  weekly: weekly,
  monthly: monthly,
);

/// Forget everything. For tests, which share one process.
void resetReminders() => RustLib.instance.api.crateApiRemindResetReminders();

/// One schedule for the platform to hand to the OS.
class ScheduleView {
  /// The id to schedule under, and to cancel by.
  final int id;

  /// `daily`, `weekly` or `monthly`.
  final String kind;
  final int hour;
  final int minute;

  /// 1 = Sunday. Only meaningful for `weekly`.
  final int? weekday;

  /// Day of month. Only meaningful for `monthly`.
  final int? day;

  const ScheduleView({
    required this.id,
    required this.kind,
    required this.hour,
    required this.minute,
    this.weekday,
    this.day,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      hour.hashCode ^
      minute.hashCode ^
      weekday.hashCode ^
      day.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScheduleView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          hour == other.hour &&
          minute == other.minute &&
          weekday == other.weekday &&
          day == other.day;
}
