// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_day`, `rows`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

RecapView recap({required List<String> ids, required List<String> daysOf}) =>
    RustLib.instance.api.crateApiReportRecap(ids: ids, daysOf: daysOf);

/// The week is **Sunday to Sunday**, which is what `getDay()` counts from.
WeeklyView weekly({
  required List<String> ids,
  required List<String> daysOf,
  required double weeklyBudget,
  required String today,
}) => RustLib.instance.api.crateApiReportWeekly(
  ids: ids,
  daysOf: daysOf,
  weeklyBudget: weeklyBudget,
  today: today,
);

/// The banner, or `None`.
///
/// `None` is the common answer and not a failure: fewer than three expenses in
/// the cycle produces nothing, because a sentence about two rows is noise
/// rather than an insight.
InsightView? insight({
  required List<String> ids,
  required List<String> daysOf,
  required String today,
  required bool zh,
  required InsightCopyView copy,
}) => RustLib.instance.api.crateApiReportInsight(
  ids: ids,
  daysOf: daysOf,
  today: today,
  zh: zh,
  copy: copy,
);

/// The sentences the banner is built from. Intl, so they come from Dart.
///
/// `%s`, `%d`, `%a`, `%b` and `%w` are each substituted **once**, left to
/// right, because the TypeScript spells it as `String.replace(string, …)` where
/// it uses one at all — and that replaces the first occurrence only.
class InsightCopyView {
  final String overBudget;
  final String nearBudget;
  final String dailyOver;
  final String catOver;
  final String topCat;
  final String creditDue;
  final String daysLeft;
  final String dueToday;

  /// `%d` days overdue.
  final String overdue;

  const InsightCopyView({
    required this.overBudget,
    required this.nearBudget,
    required this.dailyOver,
    required this.catOver,
    required this.topCat,
    required this.creditDue,
    required this.daysLeft,
    required this.dueToday,
    required this.overdue,
  });

  @override
  int get hashCode =>
      overBudget.hashCode ^
      nearBudget.hashCode ^
      dailyOver.hashCode ^
      catOver.hashCode ^
      topCat.hashCode ^
      creditDue.hashCode ^
      daysLeft.hashCode ^
      dueToday.hashCode ^
      overdue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InsightCopyView &&
          runtimeType == other.runtimeType &&
          overBudget == other.overBudget &&
          nearBudget == other.nearBudget &&
          dailyOver == other.dailyOver &&
          catOver == other.catOver &&
          topCat == other.topCat &&
          creditDue == other.creditDue &&
          daysLeft == other.daysLeft &&
          dueToday == other.dueToday &&
          overdue == other.overdue;
}

/// One sentence, or nothing at all.
class InsightView {
  /// The leading emoji.
  final String icon;
  final String text;

  /// Set when the insight is about one account, so the banner can link there.
  final String? acctId;

  const InsightView({required this.icon, required this.text, this.acctId});

  @override
  int get hashCode => icon.hashCode ^ text.hashCode ^ acctId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InsightView &&
          runtimeType == other.runtimeType &&
          icon == other.icon &&
          text == other.text &&
          acctId == other.acctId;
}

/// What a cycle came to, in six numbers.
class RecapView {
  final double exp;
  final double inc;

  /// Income less expense.
  final double net;

  /// Every entry in the cycle, **transfers included** — "how many rows are in
  /// this cycle", not "how many moved money one way".
  final int count;

  /// Distinct calendar days with an entry on them.
  final int activeDays;
  final String? topCat;

  /// Zero for a top category whose key is the empty string, which a malformed
  /// import can produce: `topCatKey ? byCat[topCatKey] : 0` is a truthiness
  /// test, so such a category is still named but reports nothing.
  final double topCatAmt;

  const RecapView({
    required this.exp,
    required this.inc,
    required this.net,
    required this.count,
    required this.activeDays,
    this.topCat,
    required this.topCatAmt,
  });

  @override
  int get hashCode =>
      exp.hashCode ^
      inc.hashCode ^
      net.hashCode ^
      count.hashCode ^
      activeDays.hashCode ^
      topCat.hashCode ^
      topCatAmt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecapView &&
          runtimeType == other.runtimeType &&
          exp == other.exp &&
          inc == other.inc &&
          net == other.net &&
          count == other.count &&
          activeDays == other.activeDays &&
          topCat == other.topCat &&
          topCatAmt == other.topCatAmt;
}

/// Spend against the weekly budget, for the week containing `today`.
class WeeklyView {
  final double spent;

  /// Budget less spend; negative once over.
  final double remaining;
  final bool over;

  /// Days left in the week, today included. Never negative.
  final PlatformInt64 daysLeft;

  /// The weekly budget divided by seven. A plain division, so zero gives zero
  /// and `NaN` gives `NaN` — neither is guarded, on either side.
  final double dailyBudget;

  const WeeklyView({
    required this.spent,
    required this.remaining,
    required this.over,
    required this.daysLeft,
    required this.dailyBudget,
  });

  @override
  int get hashCode =>
      spent.hashCode ^
      remaining.hashCode ^
      over.hashCode ^
      daysLeft.hashCode ^
      dailyBudget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeeklyView &&
          runtimeType == other.runtimeType &&
          spent == other.spent &&
          remaining == other.remaining &&
          over == other.over &&
          daysLeft == other.daysLeft &&
          dailyBudget == other.dailyBudget;
}
