// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_day`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// Split a search box into a date range, a direction, and the rest.
///
/// `today` is `y-m-d` in the device's own calendar — "上周" means the week the
/// phone thinks it is in.
ParsedQueryView parseQuery({required String query, required String today}) =>
    RustLib.instance.api.crateApiSearchParseQuery(query: query, today: today);

/// Which of `ids` match, in the order given.
///
/// The order is the caller's, not a ranking: this is a filter over the list
/// already on screen, so the rows that survive keep the position they had.
///
/// `zh` decides which language's category names the free text is matched
/// against — searching "food" in an English build should find 餐饮.
List<String> searchIds({
  required List<String> ids,
  required String text,
  String? io,
  String? cat,
  String? acct,
  PlatformInt64? fromMs,
  PlatformInt64? toMs,
  required bool zh,
}) => RustLib.instance.api.crateApiSearchSearchIds(
  ids: ids,
  text: text,
  io: io,
  cat: cat,
  acct: acct,
  fromMs: fromMs,
  toMs: toMs,
  zh: zh,
);

/// What a search box turned out to mean.
class ParsedQueryView {
  /// What is left to match as free text. Empty when the whole box was a date:
  /// the range *was* the query, so there is nothing left to match by name.
  final String text;

  /// `exp` or `inc` when the query named a direction.
  final String? io;
  final WallTime? from;
  final WallTime? to;

  const ParsedQueryView({required this.text, this.io, this.from, this.to});

  @override
  int get hashCode => text.hashCode ^ io.hashCode ^ from.hashCode ^ to.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParsedQueryView &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          io == other.io &&
          from == other.from &&
          to == other.to;
}

/// A wall-clock instant the platform has yet to place. `mo` is 1-based,
/// matching `DateTime`, not the core's 0-based month.
class WallTime {
  final int y;
  final int mo;
  final int d;
  final int h;
  final int mi;
  final int s;

  const WallTime({
    required this.y,
    required this.mo,
    required this.d,
    required this.h,
    required this.mi,
    required this.s,
  });

  @override
  int get hashCode =>
      y.hashCode ^
      mo.hashCode ^
      d.hashCode ^
      h.hashCode ^
      mi.hashCode ^
      s.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WallTime &&
          runtimeType == other.runtimeType &&
          y == other.y &&
          mo == other.mo &&
          d == other.d &&
          h == other.h &&
          mi == other.mi &&
          s == other.s;
}
