// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_day`, `rows_of`, `show_day`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

OverviewView overview({required List<String> ids}) =>
    RustLib.instance.api.crateApiStatsOverview(ids: ids);

/// Totals by category, largest first, with the naming and colour the row needs.
///
/// One call rather than a lookup per slice: the donut draws ten arcs and would
/// otherwise cross the boundary thirty times to label them.
List<SliceView> categorySlices({
  required List<String> ids,
  required String io,
  required bool zh,
}) =>
    RustLib.instance.api.crateApiStatsCategorySlices(ids: ids, io: io, zh: zh);

/// The daily trend over the last `days`, one point per day including empty ones.
///
/// `days_of` is parallel to `ids`: each entry's local calendar day, computed by
/// Dart. `today` likewise. Counting in day numbers rather than in milliseconds
/// is what keeps a daylight-saving transition from dropping a day off the axis
/// — which it did, in the shipping TypeScript, until this migration found it.
List<TrendPointView> dailyTrend({
  required List<String> ids,
  required List<String> daysOf,
  required PlatformInt64 days,
  required String today,
}) => RustLib.instance.api.crateApiStatsDailyTrend(
  ids: ids,
  daysOf: daysOf,
  days: days,
  today: today,
);

/// The weekly trend over the last `weeks`, each point dated to its Monday.
List<TrendPointView> weeklyTrend({
  required List<String> ids,
  required List<String> daysOf,
  required PlatformInt64 weeks,
  required String today,
}) => RustLib.instance.api.crateApiStatsWeeklyTrend(
  ids: ids,
  daysOf: daysOf,
  weeks: weeks,
  today: today,
);

/// Trend points as coordinates a painter can draw without arithmetic.
///
/// `series` is `"exp"`, `"inc"` or `"both"`, and it decides the maximum — a
/// series nobody is drawing does not get to set the scale.
ChartView chartPoints({
  required List<TrendPointView> points,
  required String series,
}) => RustLib.instance.api.crateApiStatsChartPoints(
  points: points,
  series: series,
);

/// A point in the chart's own coordinate box, which a painter scales.
class ChartPoint {
  final double x;
  final double y;

  const ChartPoint({required this.x, required this.y});

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChartPoint &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}

/// The line chart, ready to draw.
class ChartView {
  final List<ChartPoint> exp;
  final List<ChartPoint> inc;

  /// The tallest drawn value, never below 1. Exposed because a caller may
  /// want to label the axis with it.
  final double max;

  /// The box these coordinates live in.
  final double width;
  final double height;

  const ChartView({
    required this.exp,
    required this.inc,
    required this.max,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      exp.hashCode ^
      inc.hashCode ^
      max.hashCode ^
      width.hashCode ^
      height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChartView &&
          runtimeType == other.runtimeType &&
          exp == other.exp &&
          inc == other.inc &&
          max == other.max &&
          width == other.width &&
          height == other.height;
}

/// Expense, income, balance and how many rows are in range.
class OverviewView {
  final double exp;
  final double inc;
  final double balance;

  /// Every entry in range, **transfers included** — it answers "how many rows
  /// are here", not "how many moved money one way".
  final int count;

  const OverviewView({
    required this.exp,
    required this.inc,
    required this.balance,
    required this.count,
  });

  @override
  int get hashCode =>
      exp.hashCode ^ inc.hashCode ^ balance.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OverviewView &&
          runtimeType == other.runtimeType &&
          exp == other.exp &&
          inc == other.inc &&
          balance == other.balance &&
          count == other.count;
}

/// One slice of the category donut, with everything needed to draw it.
class SliceView {
  final String cat;

  /// The category's own name, in the caller's language.
  final String name;
  final String emoji;

  /// `#RRGGBB`.
  final String color;
  final double amt;

  /// Share of the total, 0..1.
  final double frac;

  /// Cumulative start fraction, 0..1 — where the arc begins.
  final double start;

  const SliceView({
    required this.cat,
    required this.name,
    required this.emoji,
    required this.color,
    required this.amt,
    required this.frac,
    required this.start,
  });

  @override
  int get hashCode =>
      cat.hashCode ^
      name.hashCode ^
      emoji.hashCode ^
      color.hashCode ^
      amt.hashCode ^
      frac.hashCode ^
      start.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SliceView &&
          runtimeType == other.runtimeType &&
          cat == other.cat &&
          name == other.name &&
          emoji == other.emoji &&
          color == other.color &&
          amt == other.amt &&
          frac == other.frac &&
          start == other.start;
}

/// One point of a trend line.
class TrendPointView {
  /// `y-m-d`, for the axis label Dart writes.
  final String day;
  final double exp;
  final double inc;

  const TrendPointView({
    required this.day,
    required this.exp,
    required this.inc,
  });

  @override
  int get hashCode => day.hashCode ^ exp.hashCode ^ inc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrendPointView &&
          runtimeType == other.runtimeType &&
          day == other.day &&
          exp == other.exp &&
          inc == other.inc;
}
