// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dated`, `parse_day`, `show_day`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// Summarise one account's cycle.
///
/// `None` unless it is a credit card with a statement day — and "set" is a
/// truthiness test, so a statement day of zero means unconfigured rather than
/// the zeroth of the month.
StatementView? statementOf({
  required String accountId,
  required List<String> ids,
  required List<String> daysOf,
  required String today,
}) => RustLib.instance.api.crateApiStatementStatementOf(
  accountId: accountId,
  ids: ids,
  daysOf: daysOf,
  today: today,
);

/// Cards with an unpaid statement due within `within_days`, soonest first.
///
/// Past-due cards are included, with a negative day count. Leaving them out
/// would make the one thing a reminder exists for disappear exactly when it
/// starts to matter.
List<DueView> dueWithin({
  required List<String> ids,
  required List<String> daysOf,
  required String today,
  required PlatformInt64 withinDays,
}) => RustLib.instance.api.crateApiStatementDueWithin(
  ids: ids,
  daysOf: daysOf,
  today: today,
  withinDays: withinDays,
);

/// A card with a bill coming due.
class DueView {
  final String accountId;
  final String accountName;
  final double billedDue;
  final PlatformInt64 daysToDue;
  final String dueDate;

  const DueView({
    required this.accountId,
    required this.accountName,
    required this.billedDue,
    required this.daysToDue,
    required this.dueDate,
  });

  @override
  int get hashCode =>
      accountId.hashCode ^
      accountName.hashCode ^
      billedDue.hashCode ^
      daysToDue.hashCode ^
      dueDate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DueView &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          accountName == other.accountName &&
          billedDue == other.billedDue &&
          daysToDue == other.daysToDue &&
          dueDate == other.dueDate;
}

/// Where a credit card stands in its cycle.
class StatementView {
  /// 出账日 — the day the statement closed.
  final String statementClose;

  /// 本期待还 — statement debt still unpaid.
  final double billedDue;

  /// 溢缴款 — credit balance as of the close, never negative.
  final double overpay;

  /// 未出账 — charges since the close, net of any payment beyond the bill.
  final double unbilled;

  /// 待还 — total debt right now, never negative.
  final double currentDebt;

  /// 还款日. Absent when the account has no due day set.
  final String? dueDate;

  /// Whole days from today to the due date; negative once overdue.
  final PlatformInt64? daysToDue;

  const StatementView({
    required this.statementClose,
    required this.billedDue,
    required this.overpay,
    required this.unbilled,
    required this.currentDebt,
    this.dueDate,
    this.daysToDue,
  });

  @override
  int get hashCode =>
      statementClose.hashCode ^
      billedDue.hashCode ^
      overpay.hashCode ^
      unbilled.hashCode ^
      currentDebt.hashCode ^
      dueDate.hashCode ^
      daysToDue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatementView &&
          runtimeType == other.runtimeType &&
          statementClose == other.statementClose &&
          billedDue == other.billedDue &&
          overpay == other.overpay &&
          unbilled == other.unbilled &&
          currentDebt == other.currentDebt &&
          dueDate == other.dueDate &&
          daysToDue == other.daysToDue;
}
