// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_day`, `show_day`, `store`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

/// Record an entry. Returns its id.
///
/// `id` and `now` come from Dart because identity and the clock are the
/// platform's, everywhere in this crate.
///
/// Recording also moves the current account to wherever the entry landed, so
/// the next record sheet opens there — a side effect the parity harness found
/// rather than the TypeScript announced.
String addEntry({
  required NewEntry entry,
  required String id,
  required PlatformInt64 now,
}) =>
    RustLib.instance.api.crateApiStoreAddEntry(entry: entry, id: id, now: now);

/// Edit an entry in place. Answers whether the id was found.
///
/// Every field the patch names is stamped with `now`, which is what lets two
/// devices editing *different* fields of one entry both keep their edit.
bool updateEntry({
  required String id,
  required EntryPatch patch,
  required PlatformInt64 now,
}) => RustLib.instance.api.crateApiStoreUpdateEntry(
  id: id,
  patch: patch,
  now: now,
);

/// Soft-delete an entry, returning the token that reverses it.
///
/// The row stays in the ledger as a tombstone so other devices learn of the
/// deletion; every display path filters it out. `None` means the id was
/// unknown.
UndoToken? removeEntry({required String id, required PlatformInt64 now}) =>
    RustLib.instance.api.crateApiStoreRemoveEntry(id: id, now: now);

/// Reverse a delete, as fresh stamped writes rather than a replayed snapshot.
///
/// Replaying the old rows would restore their old `updatedAt` too, which sits
/// below the push watermark — so the undo would never reach the cloud, and the
/// next pull would re-delete the entry.
void unremoveEntry({required UndoToken undo, required PlatformInt64 now}) =>
    RustLib.instance.api.crateApiStoreUnremoveEntry(undo: undo, now: now);

/// A transfer between two accounts, as one `xfer` row. Returns its id.
///
/// `io` is `xfer`, which keeps the row out of income and expense statistics —
/// moving money is neither. The current account moves unconditionally, unlike
/// [`add_entry`]: a transfer always names a `from`, so there is nothing to
/// guard against.
String addTransfer({
  required NewTransfer transfer,
  required String id,
  required PlatformInt64 now,
}) => RustLib.instance.api.crateApiStoreAddTransfer(
  transfer: transfer,
  id: id,
  now: now,
);

/// Import accepted bill rows in one write. Returns how many landed.
int importBills({
  required List<String> io,
  required List<String> cat,
  required List<double> amt,
  required List<String> note,
  required Int64List ts,
  required List<String> ids,
  required PlatformInt64 now,
}) => RustLib.instance.api.crateApiStoreImportBills(
  io: io,
  cat: cat,
  amt: amt,
  note: note,
  ts: ts,
  ids: ids,
  now: now,
);

/// Where the next entry defaults to.
void setCurrentAccount({required String id}) =>
    RustLib.instance.api.crateApiStoreSetCurrentAccount(id: id);

String currentAccount() => RustLib.instance.api.crateApiStoreCurrentAccount();

int entryCount() => RustLib.instance.api.crateApiStoreEntryCount();

EntryView? getEntry({required String id}) =>
    RustLib.instance.api.crateApiStoreGetEntry(id: id);

List<AccountView> accounts() => RustLib.instance.api.crateApiStoreAccounts();

/// Every live row, newest first. Tombstones are not included.
List<EntryView> liveEntries() =>
    RustLib.instance.api.crateApiStoreLiveEntries();

/// The entry list, grouped into calendar days and flattened for a builder.
///
/// `days` is parallel to `ids`: each entry's local calendar day, as `y-m-d`,
/// computed by Dart because the timezone is the platform's. Passing the ids
/// rather than whole entries keeps this a projection of state the store already
/// owns — Dart names which rows it is showing, not what they contain.
List<ListItem> listItems({
  required List<String> ids,
  required List<String> days,
  required String today,
  required int columns,
}) => RustLib.instance.api.crateApiStoreListItems(
  ids: ids,
  days: days,
  today: today,
  columns: columns,
);

/// Replace the whole ledger from a JSON array of entries.
///
/// The shape is the app's own on-disk format, so a Flutter build reads what a
/// React Native build wrote. Returns how many rows landed.
int loadEntries({required String json}) =>
    RustLib.instance.api.crateApiStoreLoadEntries(json: json);

/// The whole ledger as JSON, tombstones included.
///
/// Tombstones included deliberately: they are how another device learns of a
/// deletion, and a snapshot that dropped them would resurrect every deleted
/// row on the next restore.
String snapshotEntries() => RustLib.instance.api.crateApiStoreSnapshotEntries();

/// Empty the store. For tests and for sign-out.
void reset() => RustLib.instance.api.crateApiStoreReset();

/// An account, as Dart holds it.
class AccountView {
  final String id;
  final String name;
  final String? nameEn;
  final double balance;

  /// `"cash" | "credit" | "prepaid" | "fx"`, empty for the default.
  final String kind;
  final int? statementDay;
  final int? dueDay;
  final String? fxCode;
  final double? fxRate;
  final bool archived;

  const AccountView({
    required this.id,
    required this.name,
    this.nameEn,
    required this.balance,
    required this.kind,
    this.statementDay,
    this.dueDay,
    this.fxCode,
    this.fxRate,
    required this.archived,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      nameEn.hashCode ^
      balance.hashCode ^
      kind.hashCode ^
      statementDay.hashCode ^
      dueDay.hashCode ^
      fxCode.hashCode ^
      fxRate.hashCode ^
      archived.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          nameEn == other.nameEn &&
          balance == other.balance &&
          kind == other.kind &&
          statementDay == other.statementDay &&
          dueDay == other.dueDay &&
          fxCode == other.fxCode &&
          fxRate == other.fxRate &&
          archived == other.archived;
}

/// A partial edit. Every field is "leave alone" when absent.
///
/// Modelled field by field rather than as a map of strings so a typo cannot
/// silently write a field nobody reads — the same reason `core::Patch` is.
class EntryPatch {
  final PlatformInt64? ts;
  final String? io;
  final String? cat;
  final double? amt;
  final String? note;
  final String? acct;
  final String? acctTo;
  final double? fee;
  final double? discount;
  final String? subcat;
  final String? cur;
  final double? origAmt;
  final double? rate;
  final List<String>? tags;
  final String? ledger;
  final String? rb;
  final double? rbAmt;
  final double? refund;
  final String? refundOf;
  final bool? fromSub;
  final String? src;

  const EntryPatch({
    this.ts,
    this.io,
    this.cat,
    this.amt,
    this.note,
    this.acct,
    this.acctTo,
    this.fee,
    this.discount,
    this.subcat,
    this.cur,
    this.origAmt,
    this.rate,
    this.tags,
    this.ledger,
    this.rb,
    this.rbAmt,
    this.refund,
    this.refundOf,
    this.fromSub,
    this.src,
  });

  static Future<EntryPatch> default_() =>
      RustLib.instance.api.crateApiStoreEntryPatchDefault();

  @override
  int get hashCode =>
      ts.hashCode ^
      io.hashCode ^
      cat.hashCode ^
      amt.hashCode ^
      note.hashCode ^
      acct.hashCode ^
      acctTo.hashCode ^
      fee.hashCode ^
      discount.hashCode ^
      subcat.hashCode ^
      cur.hashCode ^
      origAmt.hashCode ^
      rate.hashCode ^
      tags.hashCode ^
      ledger.hashCode ^
      rb.hashCode ^
      rbAmt.hashCode ^
      refund.hashCode ^
      refundOf.hashCode ^
      fromSub.hashCode ^
      src.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryPatch &&
          runtimeType == other.runtimeType &&
          ts == other.ts &&
          io == other.io &&
          cat == other.cat &&
          amt == other.amt &&
          note == other.note &&
          acct == other.acct &&
          acctTo == other.acctTo &&
          fee == other.fee &&
          discount == other.discount &&
          subcat == other.subcat &&
          cur == other.cur &&
          origAmt == other.origAmt &&
          rate == other.rate &&
          tags == other.tags &&
          ledger == other.ledger &&
          rb == other.rb &&
          rbAmt == other.rbAmt &&
          refund == other.refund &&
          refundOf == other.refundOf &&
          fromSub == other.fromSub &&
          src == other.src;
}

/// One entry, as Dart holds it.
///
/// A flat mirror of `core::Entry` rather than a re-export: the core answers to
/// the parity corpus and its shapes are chosen to match the TypeScript it
/// replaces. The moment an FFI attribute appears there, it is answering to two
/// masters.
class EntryView {
  final String id;
  final PlatformInt64 ts;

  /// `"exp" | "inc" | "xfer"`, or empty when the row names none.
  final String io;
  final String cat;
  final double amt;
  final String? note;
  final String? acct;
  final String? acctTo;
  final double? fee;
  final double? discount;
  final String? subcat;
  final String? cur;
  final double? origAmt;
  final double? rate;
  final List<String>? tags;
  final String? ledger;

  /// `"pending" | "done"`, or absent.
  final String? rb;
  final double? rbAmt;
  final double? refund;
  final String? refundOf;
  final bool? fromSub;

  /// `"bill" | "notif"`, or absent when typed by hand.
  final String? src;
  final PlatformInt64? deletedAt;
  final PlatformInt64? updatedAt;

  const EntryView({
    required this.id,
    required this.ts,
    required this.io,
    required this.cat,
    required this.amt,
    this.note,
    this.acct,
    this.acctTo,
    this.fee,
    this.discount,
    this.subcat,
    this.cur,
    this.origAmt,
    this.rate,
    this.tags,
    this.ledger,
    this.rb,
    this.rbAmt,
    this.refund,
    this.refundOf,
    this.fromSub,
    this.src,
    this.deletedAt,
    this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      ts.hashCode ^
      io.hashCode ^
      cat.hashCode ^
      amt.hashCode ^
      note.hashCode ^
      acct.hashCode ^
      acctTo.hashCode ^
      fee.hashCode ^
      discount.hashCode ^
      subcat.hashCode ^
      cur.hashCode ^
      origAmt.hashCode ^
      rate.hashCode ^
      tags.hashCode ^
      ledger.hashCode ^
      rb.hashCode ^
      rbAmt.hashCode ^
      refund.hashCode ^
      refundOf.hashCode ^
      fromSub.hashCode ^
      src.hashCode ^
      deletedAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          ts == other.ts &&
          io == other.io &&
          cat == other.cat &&
          amt == other.amt &&
          note == other.note &&
          acct == other.acct &&
          acctTo == other.acctTo &&
          fee == other.fee &&
          discount == other.discount &&
          subcat == other.subcat &&
          cur == other.cur &&
          origAmt == other.origAmt &&
          rate == other.rate &&
          tags == other.tags &&
          ledger == other.ledger &&
          rb == other.rb &&
          rbAmt == other.rbAmt &&
          refund == other.refund &&
          refundOf == other.refundOf &&
          fromSub == other.fromSub &&
          src == other.src &&
          deletedAt == other.deletedAt &&
          updatedAt == other.updatedAt;
}

/// One row of the flattened day-grouped list.
///
/// `kind` is `"header"`, `"entry"` or `"row"`. A flat shape with a tag rather
/// than three types, because `flutter_rust_bridge` renders a Rust enum with
/// fields as a sealed Dart class hierarchy, and a `ListView.builder` reading
/// one field is easier to get right than a visitor over three.
class ListItem {
  final String kind;

  /// `y-m-d` of the day this item belongs to.
  final String day;

  /// Headers only: `"today"`, `"yesterday"` or `"date"` — *which* name the
  /// day takes. Spelling the third is `toLocaleDateString`, which is Intl and
  /// therefore Dart's.
  final String label;

  /// Headers only.
  final double exp;

  /// Headers only.
  final double inc;

  /// Entry rows: the one id. Packed rows: several.
  final List<String> ids;

  const ListItem({
    required this.kind,
    required this.day,
    required this.label,
    required this.exp,
    required this.inc,
    required this.ids,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      day.hashCode ^
      label.hashCode ^
      exp.hashCode ^
      inc.hashCode ^
      ids.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListItem &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          day == other.day &&
          label == other.label &&
          exp == other.exp &&
          inc == other.inc &&
          ids == other.ids;
}

/// A new entry, as the record sheet supplies it.
///
/// Separate from [`EntryView`] because they are not the same thing: this has no
/// `updatedAt`, no tombstone and no id — those are the store's to set, and a
/// caller that could set them could write a row the sync merge cannot reason
/// about.
class NewEntry {
  final String io;
  final String cat;
  final double amt;
  final String? note;
  final String? acct;
  final String? subcat;
  final String? cur;
  final double? origAmt;
  final double? rate;
  final List<String>? tags;
  final String? ledger;

  /// When it happened. The store's `now` when absent.
  final PlatformInt64? ts;

  const NewEntry({
    required this.io,
    required this.cat,
    required this.amt,
    this.note,
    this.acct,
    this.subcat,
    this.cur,
    this.origAmt,
    this.rate,
    this.tags,
    this.ledger,
    this.ts,
  });

  static Future<NewEntry> default_() =>
      RustLib.instance.api.crateApiStoreNewEntryDefault();

  @override
  int get hashCode =>
      io.hashCode ^
      cat.hashCode ^
      amt.hashCode ^
      note.hashCode ^
      acct.hashCode ^
      subcat.hashCode ^
      cur.hashCode ^
      origAmt.hashCode ^
      rate.hashCode ^
      tags.hashCode ^
      ledger.hashCode ^
      ts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewEntry &&
          runtimeType == other.runtimeType &&
          io == other.io &&
          cat == other.cat &&
          amt == other.amt &&
          note == other.note &&
          acct == other.acct &&
          subcat == other.subcat &&
          cur == other.cur &&
          origAmt == other.origAmt &&
          rate == other.rate &&
          tags == other.tags &&
          ledger == other.ledger &&
          ts == other.ts;
}

/// What a transfer needs. `from` and `to` are account ids.
///
/// A struct rather than ten parameters, which is not only a lint: a transfer
/// has two accounts, two optional adjustments and two optional labels, and at
/// the call site `fee` and `discount` are the same type in adjacent positions.
class NewTransfer {
  final String from;
  final String to;
  final double amt;

  /// Comes off the FROM account. A zero is no fee, not a fee of zero.
  final double? fee;

  /// Credits the TO account, same rule.
  final double? discount;
  final String? note;
  final String? ledger;

  /// When it happened; the caller's clock when absent.
  final PlatformInt64? ts;

  const NewTransfer({
    required this.from,
    required this.to,
    required this.amt,
    this.fee,
    this.discount,
    this.note,
    this.ledger,
    this.ts,
  });

  static Future<NewTransfer> default_() =>
      RustLib.instance.api.crateApiStoreNewTransferDefault();

  @override
  int get hashCode =>
      from.hashCode ^
      to.hashCode ^
      amt.hashCode ^
      fee.hashCode ^
      discount.hashCode ^
      note.hashCode ^
      ledger.hashCode ^
      ts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewTransfer &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          to == other.to &&
          amt == other.amt &&
          fee == other.fee &&
          discount == other.discount &&
          note == other.note &&
          ledger == other.ledger &&
          ts == other.ts;
}

/// What one undoable delete needs to be reversed.
///
/// Opaque to Dart on purpose: it is a token to hand back, not a thing to
/// inspect or construct. Deleting an entry also tombstones its refund incomes
/// and rewinds the original's refund counter, and a caller assembling this by
/// hand would get that wrong.
class UndoToken {
  final String id;
  final List<String> childIds;
  final String? refundedId;
  final double? prevRefund;

  const UndoToken({
    required this.id,
    required this.childIds,
    this.refundedId,
    this.prevRefund,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      childIds.hashCode ^
      refundedId.hashCode ^
      prevRefund.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UndoToken &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          childIds == other.childIds &&
          refundedId == other.refundedId &&
          prevRefund == other.prevRefund;
}
