// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `charge_entry`, `parse_day`, `set_subs_inner`, `subs_lock`, `subs_of`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`

List<SubView> subs() => RustLib.instance.api.crateApiSubscriptionsSubs();

/// Create a subscription. Returns its id.
///
/// `day` is clamped to 1..=28 and `month` to 1..=12, as the shipping form does:
/// a subscription billed on the 31st would skip February, and the picker never
/// offers one, but a restored file can say anything.
String addSub({
  required NewSub sub,
  required String id,
  required PlatformInt64 now,
}) => RustLib.instance.api.crateApiSubscriptionsAddSub(
  sub: sub,
  id: id,
  now: now,
);

bool removeSub({required String id}) =>
    RustLib.instance.api.crateApiSubscriptionsRemoveSub(id: id);

/// The next charge date at or after `from`, as `YYYY-M-D` with a 0-indexed
/// month — the same encoding the cursor uses.
///
/// A day past the end of a month **overflows** rather than clamping, because
/// `new Date(y, m, 31)` does: a subscription billed on the 31st charges on
/// 3 March in a non-leap year, not on the 28th of February.
String? subNextDue({required String id, required String from}) =>
    RustLib.instance.api.crateApiSubscriptionsSubNextDue(id: id, from: from);

PendingCharges subsPending({
  required List<String> starts,
  required String today,
}) => RustLib.instance.api.crateApiSubscriptionsSubsPending(
  starts: starts,
  today: today,
);

/// Post the charges and advance the cursors. Returns the names that fired.
///
/// `days` and `epochs` are parallel: the timestamp Dart computed for each
/// calendar day. The plan is recomputed from `starts` and `today` rather than
/// remembered from [`subs_pending`], so the two calls cannot disagree about
/// what was due — and a day with no epoch supplied is skipped rather than
/// guessed at.
List<String> subsCommit({
  required List<String> starts,
  required String today,
  required List<String> days,
  required Int64List epochs,
  required PlatformInt64 now,
}) => RustLib.instance.api.crateApiSubscriptionsSubsCommit(
  starts: starts,
  today: today,
  days: days,
  epochs: epochs,
  now: now,
);

/// A subscription to create.
///
/// A struct rather than thirteen parameters, for the reason `NewTransfer` is
/// one: half of these are optional and several are the same type in adjacent
/// positions, which at a call site is an invitation to swap two of them.
class NewSub {
  final String name;
  final double amt;

  /// `monthly` | `yearly`.
  final String freq;
  final int day;
  final int? month;
  final String cat;
  final String emoji;

  /// Posts a transfer between `from` and `to` instead of an expense.
  final bool isTransfer;
  final String? from;
  final String? to;

  /// Total instalments. Absent or zero is open-ended.
  final int? periods;

  const NewSub({
    required this.name,
    required this.amt,
    required this.freq,
    required this.day,
    this.month,
    required this.cat,
    required this.emoji,
    required this.isTransfer,
    this.from,
    this.to,
    this.periods,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      amt.hashCode ^
      freq.hashCode ^
      day.hashCode ^
      month.hashCode ^
      cat.hashCode ^
      emoji.hashCode ^
      isTransfer.hashCode ^
      from.hashCode ^
      to.hashCode ^
      periods.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewSub &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          amt == other.amt &&
          freq == other.freq &&
          day == other.day &&
          month == other.month &&
          cat == other.cat &&
          emoji == other.emoji &&
          isTransfer == other.isTransfer &&
          from == other.from &&
          to == other.to &&
          periods == other.periods;
}

/// Every date that would be charged, and every cursor that would move.
///
/// `starts` is parallel to [`subs`]: where each subscription's cursor sits,
/// as a calendar day. Decoding it from `lastCharged` is arithmetic, but
/// falling back to the day `created` names is a conversion from an epoch —
/// which needs a timezone, so Dart supplies the answer.
///
/// Nothing is written. This exists so the platform can turn the dates into
/// timestamps before [`subs_commit`] posts anything.
class PendingCharges {
  /// Parallel with [`Self::days`]: which subscription each charge belongs to.
  final List<String> subIds;

  /// `YYYY-M-D`, 0-indexed month, oldest first.
  final List<String> days;

  /// Subscriptions whose cursor moves without posting anything — a fully-paid
  /// instalment still advances, and that has to be stored or it is recomputed
  /// on every launch.
  final List<String> cursorOnly;

  const PendingCharges({
    required this.subIds,
    required this.days,
    required this.cursorOnly,
  });

  static Future<PendingCharges> default_() =>
      RustLib.instance.api.crateApiSubscriptionsPendingChargesDefault();

  @override
  int get hashCode => subIds.hashCode ^ days.hashCode ^ cursorOnly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingCharges &&
          runtimeType == other.runtimeType &&
          subIds == other.subIds &&
          days == other.days &&
          cursorOnly == other.cursorOnly;
}

/// One subscription, as Dart holds it.
class SubView {
  final String id;
  final String name;
  final String emoji;
  final double amt;

  /// `monthly` | `yearly`.
  final String freq;

  /// Day of the month, 1..=28.
  final int day;

  /// Charge month for a yearly sub, 1..=12.
  final int? month;
  final String cat;
  final PlatformInt64 created;

  /// `YYYY-M-D` with a **0-indexed** month, inherited from v7. Empty when the
  /// subscription has never fired.
  final String lastCharged;

  /// A transfer posts between two accounts instead of an expense.
  final bool isTransfer;
  final String? from;
  final String? to;

  /// Total instalments, or none for an open-ended subscription.
  final int? periods;
  final int charged;

  const SubView({
    required this.id,
    required this.name,
    required this.emoji,
    required this.amt,
    required this.freq,
    required this.day,
    this.month,
    required this.cat,
    required this.created,
    required this.lastCharged,
    required this.isTransfer,
    this.from,
    this.to,
    this.periods,
    required this.charged,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      emoji.hashCode ^
      amt.hashCode ^
      freq.hashCode ^
      day.hashCode ^
      month.hashCode ^
      cat.hashCode ^
      created.hashCode ^
      lastCharged.hashCode ^
      isTransfer.hashCode ^
      from.hashCode ^
      to.hashCode ^
      periods.hashCode ^
      charged.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          emoji == other.emoji &&
          amt == other.amt &&
          freq == other.freq &&
          day == other.day &&
          month == other.month &&
          cat == other.cat &&
          created == other.created &&
          lastCharged == other.lastCharged &&
          isTransfer == other.isTransfer &&
          from == other.from &&
          to == other.to &&
          periods == other.periods &&
          charged == other.charged;
}
