// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_sections`, `channel_name`, `dispatch`, `effect`, `engine`, `ledger_values`, `pending_blob`, `pending`, `rows_json`, `set_pending`, `timer_name`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

/// A session appeared. The ledger must already be loaded — see the module docs.
List<SyncEffect> syncSignIn({required String userId}) =>
    RustLib.instance.api.crateApiSyncSyncSignIn(userId: userId);

List<SyncEffect> syncSignOut() =>
    RustLib.instance.api.crateApiSyncSyncSignOut();

/// The entries read came back. `json` is `None` when it **failed** — which is
/// not the same as an empty table, and collapsing the two is how a device ends
/// up pushing its defaults over an account that already had data.
List<SyncEffect> syncEntriesPulled({String? json}) =>
    RustLib.instance.api.crateApiSyncSyncEntriesPulled(json: json);

List<SyncEffect> syncPulledPushDone({required bool ok}) =>
    RustLib.instance.api.crateApiSyncSyncPulledPushDone(ok: ok);

/// The config read came back. `ok` false is a failed read; `ok` true with no
/// `json` is an account that has no config yet.
List<SyncEffect> syncConfigPulled({required bool ok, String? json}) =>
    RustLib.instance.api.crateApiSyncSyncConfigPulled(ok: ok, json: json);

List<SyncEffect> syncConfigPushDone({required bool ok}) =>
    RustLib.instance.api.crateApiSyncSyncConfigPushDone(ok: ok);

/// How far a flush got: `entriesFailed` | `configFailed` | `ok`.
///
/// Three outcomes rather than a boolean, because the watermark advances past
/// rows that were persisted even when the config upload after them fails.
List<SyncEffect> syncFlushDone({required String outcome}) =>
    RustLib.instance.api.crateApiSyncSyncFlushDone(outcome: outcome);

/// The user changed something. `sections` names the config sections touched; an
/// entry-only edit passes an empty list.
List<SyncEffect> syncLocalEdit({
  required List<String> sections,
  required PlatformInt64 now,
}) => RustLib.instance.api.crateApiSyncSyncLocalEdit(
  sections: sections,
  now: now,
);

/// A row arrived on the entries channel.
List<SyncEffect> syncRealtimeEntry({required String json}) =>
    RustLib.instance.api.crateApiSyncSyncRealtimeEntry(json: json);

/// A blob arrived on the config channel.
List<SyncEffect> syncRealtimeConfig({required String json}) =>
    RustLib.instance.api.crateApiSyncSyncRealtimeConfig(json: json);

/// `debounce` or `retry` elapsed.
List<SyncEffect> syncTimerFired({required String timer}) =>
    RustLib.instance.api.crateApiSyncSyncTimerFired(timer: timer);

/// The "retry sync" button.
List<SyncEffect> syncRetryNow() =>
    RustLib.instance.api.crateApiSyncSyncRetryNow();

/// The config blob to upload: the store's config plus the section stamps.
String syncConfigBlob() => RustLib.instance.api.crateApiSyncSyncConfigBlob();

/// The section stamps, for the platform to persist.
String syncStampsJson() => RustLib.instance.api.crateApiSyncSyncStampsJson();

/// Restore the stamps at boot, **before** the first sign-in.
///
/// They track local edits regardless of session, so an edit made offline and
/// signed out still has to beat a stale cloud section after the next sign-in.
void syncLoadStamps({required String json}) =>
    RustLib.instance.api.crateApiSyncSyncLoadStamps(json: json);

/// `off` | `syncing` | `synced` | `error`.
String syncStatus() => RustLib.instance.api.crateApiSyncSyncStatus();

/// The config sections, in the order the merge considers them. Dart names these
/// when it reports a local edit.
List<String> syncSections() => RustLib.instance.api.crateApiSyncSyncSections();

/// Throw the engine away — for tests, and for a sign-out that must not leave a
/// watermark behind.
void syncReset() => RustLib.instance.api.crateApiSyncSyncReset();

/// One thing for Dart to do.
///
/// A tagged struct rather than an enum with payloads: the payloads are all
/// either a JSON string, a name, or a number, and one flat shape crosses more
/// cleanly than twelve variants would.
class SyncEffect {
  /// `pullEntries` | `pullConfig` | `pushPulled` | `pushConfig` | `flush`
  /// | `subscribe` | `unsubscribe` | `setTimer` | `clearTimer` | `status`
  /// | `lastSync` | `saveStamps`
  final String kind;

  /// Rows to upload, as a JSON array. Empty when the effect carries none.
  ///
  /// A `flush` with an empty array still has to happen: the config is pushed
  /// either way, and that is what makes an accounts-only change reach the
  /// cloud.
  final String json;

  /// `entries` | `config` for the channels, `debounce` | `retry` for the
  /// timers, the status name for `status`.
  final String name;

  /// Milliseconds, for `setTimer` only.
  final PlatformInt64 ms;

  const SyncEffect({
    required this.kind,
    required this.json,
    required this.name,
    required this.ms,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ json.hashCode ^ name.hashCode ^ ms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncEffect &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          json == other.json &&
          name == other.name &&
          ms == other.ms;
}
