// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `accounts_json`, `as_str`, `empty`, `failed`, `merge_accounts`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

/// The document to write out: this device's whole ledger, plus its accounts.
///
/// The whole ledger rather than a delta, because a file has no memory of what
/// the other device already saw. Tombstones included — they are how the other
/// device learns of a deletion, and a document that dropped them would
/// resurrect everything either side had ever deleted.
String syncDocument({required PlatformInt64 now}) =>
    RustLib.instance.api.crateApiSyncSyncDocument(now: now);

/// Merge a document written by another device into this one.
///
/// The local ledger is replaced by the merge of both, which is not the same as
/// "the document is imported": a row this device has and the document does not
/// survives, and a row the document has that this device deleted stays
/// deleted, because the tombstone is newer than the row.
SyncReport mergeDocument({required String json}) =>
    RustLib.instance.api.crateApiSyncMergeDocument(json: json);

/// Whether a document can be read at all, without merging it.
///
/// For a preview: a person about to merge a file into their ledger should be
/// able to see how many entries are in it first.
SyncReport inspectDocument({required String json}) =>
    RustLib.instance.api.crateApiSyncInspectDocument(json: json);

/// What a merge did, in the terms a person would ask about it.
class SyncReport {
  /// Empty when it worked; otherwise why it did not.
  final String error;

  /// Rows this device did not have.
  final PlatformInt64 added;

  /// Rows both sides had, where the merge chose something different from
  /// what was here.
  final PlatformInt64 updated;

  /// Rows where both sides had edited the same entry. Resolved — this is a
  /// count of decisions made, not of problems left.
  final PlatformInt64 conflicts;

  /// Accounts brought across.
  final PlatformInt64 accountsAdded;

  /// Rows in the document, whatever happened to them.
  final PlatformInt64 incoming;

  const SyncReport({
    required this.error,
    required this.added,
    required this.updated,
    required this.conflicts,
    required this.accountsAdded,
    required this.incoming,
  });

  @override
  int get hashCode =>
      error.hashCode ^
      added.hashCode ^
      updated.hashCode ^
      conflicts.hashCode ^
      accountsAdded.hashCode ^
      incoming.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncReport &&
          runtimeType == other.runtimeType &&
          error == other.error &&
          added == other.added &&
          updated == other.updated &&
          conflicts == other.conflicts &&
          accountsAdded == other.accountsAdded &&
          incoming == other.incoming;
}
