// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `choice`, `view`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Choice`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// The palette in force.
ThemeView currentTheme() => RustLib.instance.api.crateApiThemeCurrentTheme();

/// One particular palette, for a picker that wants to draw a preview of a
/// theme nobody has chosen yet.
ThemeView themeOf({required String key, required bool dark}) =>
    RustLib.instance.api.crateApiThemeThemeOf(key: key, dark: dark);

/// Which flower is chosen. An unknown stored key reads back as `default`,
/// which is what a config written by a build with one more flower should do.
String themeKey() => RustLib.instance.api.crateApiThemeThemeKey();

bool isDark() => RustLib.instance.api.crateApiThemeIsDark();

void setTheme({required String key, required bool dark}) =>
    RustLib.instance.api.crateApiThemeSetTheme(key: key, dark: dark);

/// Every theme, in the order the picker shows them.
List<ThemeOption> themeOptions() =>
    RustLib.instance.api.crateApiThemeThemeOptions();

/// A theme the picker offers: its key and the accent it is recognised by.
class ThemeOption {
  final String key;
  final String swatch;

  const ThemeOption({required this.key, required this.swatch});

  @override
  int get hashCode => key.hashCode ^ swatch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThemeOption &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          swatch == other.swatch;
}

/// One palette, as strings. `#RRGGBB`, `#RRGGBBAA` or `rgba(…)` — parsing them
/// is the platform's, and `theme.dart` already has both functions for it.
class ThemeView {
  final String hibiscus;
  final String hibiscusDeep;
  final String hibiscusSoft;
  final String stamen;
  final String leaf;
  final String leafDeep;
  final String paper;
  final String paperWarm;
  final String ink;
  final String inkSoft;
  final String line;
  final String card;
  final String tint;
  final String tintStrong;
  final String gradFrom;
  final String gradTo;
  final String shadow;
  final String glow;
  final String overlay;
  final bool isDark;

  const ThemeView({
    required this.hibiscus,
    required this.hibiscusDeep,
    required this.hibiscusSoft,
    required this.stamen,
    required this.leaf,
    required this.leafDeep,
    required this.paper,
    required this.paperWarm,
    required this.ink,
    required this.inkSoft,
    required this.line,
    required this.card,
    required this.tint,
    required this.tintStrong,
    required this.gradFrom,
    required this.gradTo,
    required this.shadow,
    required this.glow,
    required this.overlay,
    required this.isDark,
  });

  @override
  int get hashCode =>
      hibiscus.hashCode ^
      hibiscusDeep.hashCode ^
      hibiscusSoft.hashCode ^
      stamen.hashCode ^
      leaf.hashCode ^
      leafDeep.hashCode ^
      paper.hashCode ^
      paperWarm.hashCode ^
      ink.hashCode ^
      inkSoft.hashCode ^
      line.hashCode ^
      card.hashCode ^
      tint.hashCode ^
      tintStrong.hashCode ^
      gradFrom.hashCode ^
      gradTo.hashCode ^
      shadow.hashCode ^
      glow.hashCode ^
      overlay.hashCode ^
      isDark.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThemeView &&
          runtimeType == other.runtimeType &&
          hibiscus == other.hibiscus &&
          hibiscusDeep == other.hibiscusDeep &&
          hibiscusSoft == other.hibiscusSoft &&
          stamen == other.stamen &&
          leaf == other.leaf &&
          leafDeep == other.leafDeep &&
          paper == other.paper &&
          paperWarm == other.paperWarm &&
          ink == other.ink &&
          inkSoft == other.inkSoft &&
          line == other.line &&
          card == other.card &&
          tint == other.tint &&
          tintStrong == other.tintStrong &&
          gradFrom == other.gradFrom &&
          gradTo == other.gradTo &&
          shadow == other.shadow &&
          glow == other.glow &&
          overlay == other.overlay &&
          isDark == other.isDark;
}
