// Every integration test, under one entrypoint.
//
// Running them a file at a time builds and installs a whole APK per file.
// At 42 files that was 42 builds for a suite whose execution takes
// seconds — about twenty minutes, nearly all of it Gradle. Worse than slow:
// twenty minutes is twenty minutes in which the emulator can die, and twice
// it did, costing the whole run rather than part of it. One entrypoint,
// one build, about five minutes.
//
// Each file still stands alone and can still be run by itself. That is the
// right thing to run while working on one screen; this is the right thing
// to run before committing.
//
// Each file goes inside its OWN group, which is not cosmetic. A top-level
// setUp in a file's main() is scoped to the whole SUITE, not to that file,
// so calling the mains directly made every file's setUp run before every
// other file's tests: account_detail_test creates two accounts in its
// setUp, and that quietly broke four accounts_test cases that count how
// many accounts exist. A group scopes setUp to itself — the isolation a
// separate process used to provide for free.
//
// GENERATED by scripts/gen-all-tests.js — do not edit. Adding a test file
// means re-running it; --check fails when this file is stale.

import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'account_detail_test.dart' as account_detail_test;
import 'accounts_test.dart' as accounts_test;
import 'assets_test.dart' as assets_test;
import 'backup_test.dart' as backup_test;
import 'batch_test.dart' as batch_test;
import 'bridge_test.dart' as bridge_test;
import 'budget_test.dart' as budget_test;
import 'burst_test.dart' as burst_test;
import 'calendar_test.dart' as calendar_test;
import 'capture_test.dart' as capture_test;
import 'currency_test.dart' as currency_test;
import 'edit_test.dart' as edit_test;
import 'entry_list_test.dart' as entry_list_test;
import 'export_test.dart' as export_test;
import 'history_test.dart' as history_test;
import 'home_test.dart' as home_test;
import 'import_test.dart' as import_test;
import 'ledger_days_test.dart' as ledger_days_test;
import 'library_test.dart' as library_test;
import 'liquid_test.dart' as liquid_test;
import 'lock_test.dart' as lock_test;
import 'period_test.dart' as period_test;
import 'persistence_test.dart' as persistence_test;
import 'rates_test.dart' as rates_test;
import 'record_sheet_test.dart' as record_sheet_test;
import 'reimburse_test.dart' as reimburse_test;
import 'remind_test.dart' as remind_test;
import 'report_test.dart' as report_test;
import 'scale_test.dart' as scale_test;
import 'search_test.dart' as search_test;
import 'segmented_test.dart' as segmented_test;
import 'settings_test.dart' as settings_test;
import 'sheet_extras_test.dart' as sheet_extras_test;
import 'shell_test.dart' as shell_test;
import 'statement_test.dart' as statement_test;
import 'stats_test.dart' as stats_test;
import 'store_test.dart' as store_test;
import 'subs_test.dart' as subs_test;
import 'sync_test.dart' as sync_test;
import 'theme_test.dart' as theme_test;
import 'warn_test.dart' as warn_test;
import 'widget_test.dart' as widget_test;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('account_detail_test', account_detail_test.main);
  group('accounts_test', accounts_test.main);
  group('assets_test', assets_test.main);
  group('backup_test', backup_test.main);
  group('batch_test', batch_test.main);
  group('bridge_test', bridge_test.main);
  group('budget_test', budget_test.main);
  group('burst_test', burst_test.main);
  group('calendar_test', calendar_test.main);
  group('capture_test', capture_test.main);
  group('currency_test', currency_test.main);
  group('edit_test', edit_test.main);
  group('entry_list_test', entry_list_test.main);
  group('export_test', export_test.main);
  group('history_test', history_test.main);
  group('home_test', home_test.main);
  group('import_test', import_test.main);
  group('ledger_days_test', ledger_days_test.main);
  group('library_test', library_test.main);
  group('liquid_test', liquid_test.main);
  group('lock_test', lock_test.main);
  group('period_test', period_test.main);
  group('persistence_test', persistence_test.main);
  group('rates_test', rates_test.main);
  group('record_sheet_test', record_sheet_test.main);
  group('reimburse_test', reimburse_test.main);
  group('remind_test', remind_test.main);
  group('report_test', report_test.main);
  group('scale_test', scale_test.main);
  group('search_test', search_test.main);
  group('segmented_test', segmented_test.main);
  group('settings_test', settings_test.main);
  group('sheet_extras_test', sheet_extras_test.main);
  group('shell_test', shell_test.main);
  group('statement_test', statement_test.main);
  group('stats_test', stats_test.main);
  group('store_test', store_test.main);
  group('subs_test', subs_test.main);
  group('sync_test', sync_test.main);
  group('theme_test', theme_test.main);
  group('warn_test', warn_test.main);
  group('widget_test', widget_test.main);
}
