#!/usr/bin/env node
// Emits the Rust half of the GBK decode table from the TypeScript one.
//
// The table is pure data — 126 lead bytes × 190 trail bytes = 23,940 cells,
// generated originally from the WHATWG/ICU 'gbk' decoder so the pure-JS
// fallback matches platform decoders exactly. Rust needs the same table for the
// same reason Hermes did: neither has a GBK decoder, and 支付宝 exports its
// CSVs in GBK.
//
// The one thing this script checks rather than assumes: that every cell is a
// single UTF-16 code unit. `GBK_INDEX[i]` on the JavaScript side indexes by
// code UNIT, so one astral character anywhere in the table would shift every
// lookup after it — silently, and only for the characters past that point.

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const { GBK_INDEX } = require('./_gbk-load');

const CELLS = 126 * 190;

if (GBK_INDEX.length !== CELLS) {
  console.error(
    `REFUSING: the table is ${GBK_INDEX.length} code units, not ${CELLS}.\n` +
      'Either the generator changed or a cell is an astral character, and ' +
      'every lookup past it would be off by one.',
  );
  process.exit(1);
}
for (let i = 0; i < GBK_INDEX.length; i++) {
  const c = GBK_INDEX.codePointAt(i);
  if (c >= 0xd800 && c <= 0xdfff) {
    console.error(`REFUSING: cell ${i} is a surrogate (U+${c.toString(16)}).`);
    process.exit(1);
  }
}

// Emitted as an array of u16 rather than as a string literal: Rust indexes a
// `&str` by BYTE, and these are three bytes each in UTF-8, so a string would
// need decoding at every lookup to do what the JavaScript does in one step.
const parts = [];
for (let i = 0; i < GBK_INDEX.length; i += 16) {
  const row = [];
  for (let j = i; j < Math.min(i + 16, GBK_INDEX.length); j++) {
    row.push(`0x${GBK_INDEX.charCodeAt(j).toString(16).padStart(4, '0')}`);
  }
  parts.push('    ' + row.join(', ') + ',');
}

const out = `//! The GBK decode table. **Generated by \`scripts/gen-gbk-rs.js\`** — do not
//! edit by hand.
//!
//! 126 lead bytes × 190 trail bytes = ${CELLS} cells, taken from the WHATWG/ICU
//! \`gbk\` decoder so this matches a platform decoder exactly. \`U+FFFD\` marks a
//! pair that decodes to nothing.
//!
//! Stored as code points rather than as a string, because the JavaScript side
//! indexes \`GBK_INDEX\` by UTF-16 code unit and Rust indexes a \`&str\` by byte.
//! The generator refuses to emit a table containing an astral character for the
//! same reason: one would shift every lookup after it.

/// One entry per (lead, trail) pair. See [\`crate::encoding::decode_gbk\`].
///
/// \`static\` rather than \`const\`: a const of this size is copied in at every
/// use site, which is 48 KiB of duplication per lookup call.
pub static GBK_INDEX: [u16; ${CELLS}] = [
${parts.join('\n')}
];
`;

const dest = path.join(ROOT, 'rust', 'core', 'src', 'gbk_table.rs');
fs.writeFileSync(dest, out);
console.log(
  `${CELLS} cells → ${path.relative(ROOT, dest)} (${(out.length / 1024) | 0} KiB)`,
);
