// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/accounts.dart';
import 'api/acct.dart';
import 'api/backup.dart';
import 'api/budget.dart';
import 'api/calc.dart';
import 'api/capture.dart';
import 'api/catalog.dart';
import 'api/currency.dart';
import 'api/db.dart';
import 'api/export.dart';
import 'api/glass.dart';
import 'api/history.dart';
import 'api/imports.dart';
import 'api/lock.dart';
import 'api/money.dart';
import 'api/networth.dart';
import 'api/period.dart';
import 'api/rates.dart';
import 'api/record.dart';
import 'api/reimburse.dart';
import 'api/remind.dart';
import 'api/report.dart';
import 'api/search.dart';
import 'api/statement.dart';
import 'api/stats.dart';
import 'api/store.dart';
import 'api/subscriptions.dart';
import 'api/sync.dart';
import 'api/theme.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountBalance dco_decode_account_balance(dynamic raw);

  @protected
  AccountView dco_decode_account_view(dynamic raw);

  @protected
  AcctRowView dco_decode_acct_row_view(dynamic raw);

  @protected
  AssetView dco_decode_asset_view(dynamic raw);

  @protected
  BackupInfoView dco_decode_backup_info_view(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  CategoryView dco_decode_box_autoadd_category_view(dynamic raw);

  @protected
  EntryPatch dco_decode_box_autoadd_entry_patch(dynamic raw);

  @protected
  EntryView dco_decode_box_autoadd_entry_view(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  FormView dco_decode_box_autoadd_form_view(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  InsightCopyView dco_decode_box_autoadd_insight_copy_view(dynamic raw);

  @protected
  InsightView dco_decode_box_autoadd_insight_view(dynamic raw);

  @protected
  NewEntry dco_decode_box_autoadd_new_entry(dynamic raw);

  @protected
  NewSub dco_decode_box_autoadd_new_sub(dynamic raw);

  @protected
  NewTransfer dco_decode_box_autoadd_new_transfer(dynamic raw);

  @protected
  RefundState dco_decode_box_autoadd_refund_state(dynamic raw);

  @protected
  SettingsView dco_decode_box_autoadd_settings_view(dynamic raw);

  @protected
  StatementView dco_decode_box_autoadd_statement_view(dynamic raw);

  @protected
  TemplateDraftView dco_decode_box_autoadd_template_draft_view(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  UndoToken dco_decode_box_autoadd_undo_token(dynamic raw);

  @protected
  WallTime dco_decode_box_autoadd_wall_time(dynamic raw);

  @protected
  BudgetSettings dco_decode_budget_settings(dynamic raw);

  @protected
  CandidateView dco_decode_candidate_view(dynamic raw);

  @protected
  CatBudgetView dco_decode_cat_budget_view(dynamic raw);

  @protected
  CatLabel dco_decode_cat_label(dynamic raw);

  @protected
  CategoryView dco_decode_category_view(dynamic raw);

  @protected
  ChartPoint dco_decode_chart_point(dynamic raw);

  @protected
  ChartView dco_decode_chart_view(dynamic raw);

  @protected
  ClaimList dco_decode_claim_list(dynamic raw);

  @protected
  ClaimView dco_decode_claim_view(dynamic raw);

  @protected
  DrainSummary dco_decode_drain_summary(dynamic raw);

  @protected
  DueView dco_decode_due_view(dynamic raw);

  @protected
  EntryPatch dco_decode_entry_patch(dynamic raw);

  @protected
  EntryView dco_decode_entry_view(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FormView dco_decode_form_view(dynamic raw);

  @protected
  GlassLevel dco_decode_glass_level(dynamic raw);

  @protected
  GlassSpec dco_decode_glass_spec(dynamic raw);

  @protected
  GlassTier dco_decode_glass_tier(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImportPreview dco_decode_import_preview(dynamic raw);

  @protected
  InsightCopyView dco_decode_insight_copy_view(dynamic raw);

  @protected
  InsightView dco_decode_insight_view(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AccountBalance> dco_decode_list_account_balance(dynamic raw);

  @protected
  List<AccountView> dco_decode_list_account_view(dynamic raw);

  @protected
  List<AcctRowView> dco_decode_list_acct_row_view(dynamic raw);

  @protected
  List<AssetView> dco_decode_list_asset_view(dynamic raw);

  @protected
  List<BackupInfoView> dco_decode_list_backup_info_view(dynamic raw);

  @protected
  List<CandidateView> dco_decode_list_candidate_view(dynamic raw);

  @protected
  List<CatBudgetView> dco_decode_list_cat_budget_view(dynamic raw);

  @protected
  List<CategoryView> dco_decode_list_category_view(dynamic raw);

  @protected
  List<ChartPoint> dco_decode_list_chart_point(dynamic raw);

  @protected
  List<ClaimView> dco_decode_list_claim_view(dynamic raw);

  @protected
  List<DueView> dco_decode_list_due_view(dynamic raw);

  @protected
  List<EntryView> dco_decode_list_entry_view(dynamic raw);

  @protected
  ListItem dco_decode_list_item(dynamic raw);

  @protected
  List<ListItem> dco_decode_list_list_item(dynamic raw);

  @protected
  List<LoanView> dco_decode_list_loan_view(dynamic raw);

  @protected
  List<LockAction> dco_decode_list_lock_action(dynamic raw);

  @protected
  List<PendingView> dco_decode_list_pending_view(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_64_loose(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RateView> dco_decode_list_rate_view(dynamic raw);

  @protected
  List<RawNotifView> dco_decode_list_raw_notif_view(dynamic raw);

  @protected
  List<(String, double)> dco_decode_list_record_string_f_64(dynamic raw);

  @protected
  List<RowErrorView> dco_decode_list_row_error_view(dynamic raw);

  @protected
  List<ScheduleView> dco_decode_list_schedule_view(dynamic raw);

  @protected
  List<SliceView> dco_decode_list_slice_view(dynamic raw);

  @protected
  List<SubView> dco_decode_list_sub_view(dynamic raw);

  @protected
  List<TemplateView> dco_decode_list_template_view(dynamic raw);

  @protected
  List<ThemeOption> dco_decode_list_theme_option(dynamic raw);

  @protected
  List<TrendPointView> dco_decode_list_trend_point_view(dynamic raw);

  @protected
  List<UnparsedView> dco_decode_list_unparsed_view(dynamic raw);

  @protected
  LoanView dco_decode_loan_view(dynamic raw);

  @protected
  LockAction dco_decode_lock_action(dynamic raw);

  @protected
  NetWorthView dco_decode_net_worth_view(dynamic raw);

  @protected
  NewEntry dco_decode_new_entry(dynamic raw);

  @protected
  NewSub dco_decode_new_sub(dynamic raw);

  @protected
  NewTransfer dco_decode_new_transfer(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  EntryView? dco_decode_opt_box_autoadd_entry_view(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  InsightView? dco_decode_opt_box_autoadd_insight_view(dynamic raw);

  @protected
  RefundState? dco_decode_opt_box_autoadd_refund_state(dynamic raw);

  @protected
  StatementView? dco_decode_opt_box_autoadd_statement_view(dynamic raw);

  @protected
  TemplateDraftView? dco_decode_opt_box_autoadd_template_draft_view(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  UndoToken? dco_decode_opt_box_autoadd_undo_token(dynamic raw);

  @protected
  WallTime? dco_decode_opt_box_autoadd_wall_time(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  OverviewView dco_decode_overview_view(dynamic raw);

  @protected
  ParsedQueryView dco_decode_parsed_query_view(dynamic raw);

  @protected
  PendingCharges dco_decode_pending_charges(dynamic raw);

  @protected
  PendingView dco_decode_pending_view(dynamic raw);

  @protected
  RateView dco_decode_rate_view(dynamic raw);

  @protected
  RawNotifView dco_decode_raw_notif_view(dynamic raw);

  @protected
  RecapView dco_decode_recap_view(dynamic raw);

  @protected
  (String, double) dco_decode_record_string_f_64(dynamic raw);

  @protected
  RefundState dco_decode_refund_state(dynamic raw);

  @protected
  ResolvedRate dco_decode_resolved_rate(dynamic raw);

  @protected
  RestoreResult dco_decode_restore_result(dynamic raw);

  @protected
  RowErrorView dco_decode_row_error_view(dynamic raw);

  @protected
  SaveResult dco_decode_save_result(dynamic raw);

  @protected
  ScheduleView dco_decode_schedule_view(dynamic raw);

  @protected
  SettingsView dco_decode_settings_view(dynamic raw);

  @protected
  SliceView dco_decode_slice_view(dynamic raw);

  @protected
  StatementView dco_decode_statement_view(dynamic raw);

  @protected
  SubView dco_decode_sub_view(dynamic raw);

  @protected
  SyncReport dco_decode_sync_report(dynamic raw);

  @protected
  TemplateDraftView dco_decode_template_draft_view(dynamic raw);

  @protected
  TemplateView dco_decode_template_view(dynamic raw);

  @protected
  ThemeOption dco_decode_theme_option(dynamic raw);

  @protected
  ThemeView dco_decode_theme_view(dynamic raw);

  @protected
  TierView dco_decode_tier_view(dynamic raw);

  @protected
  TrendPointView dco_decode_trend_point_view(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UndoToken dco_decode_undo_token(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UnparsedView dco_decode_unparsed_view(dynamic raw);

  @protected
  WallTime dco_decode_wall_time(dynamic raw);

  @protected
  WeeklyView dco_decode_weekly_view(dynamic raw);

  @protected
  WindowView dco_decode_window_view(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountBalance sse_decode_account_balance(SseDeserializer deserializer);

  @protected
  AccountView sse_decode_account_view(SseDeserializer deserializer);

  @protected
  AcctRowView sse_decode_acct_row_view(SseDeserializer deserializer);

  @protected
  AssetView sse_decode_asset_view(SseDeserializer deserializer);

  @protected
  BackupInfoView sse_decode_backup_info_view(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CategoryView sse_decode_box_autoadd_category_view(
    SseDeserializer deserializer,
  );

  @protected
  EntryPatch sse_decode_box_autoadd_entry_patch(SseDeserializer deserializer);

  @protected
  EntryView sse_decode_box_autoadd_entry_view(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FormView sse_decode_box_autoadd_form_view(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  InsightCopyView sse_decode_box_autoadd_insight_copy_view(
    SseDeserializer deserializer,
  );

  @protected
  InsightView sse_decode_box_autoadd_insight_view(SseDeserializer deserializer);

  @protected
  NewEntry sse_decode_box_autoadd_new_entry(SseDeserializer deserializer);

  @protected
  NewSub sse_decode_box_autoadd_new_sub(SseDeserializer deserializer);

  @protected
  NewTransfer sse_decode_box_autoadd_new_transfer(SseDeserializer deserializer);

  @protected
  RefundState sse_decode_box_autoadd_refund_state(SseDeserializer deserializer);

  @protected
  SettingsView sse_decode_box_autoadd_settings_view(
    SseDeserializer deserializer,
  );

  @protected
  StatementView sse_decode_box_autoadd_statement_view(
    SseDeserializer deserializer,
  );

  @protected
  TemplateDraftView sse_decode_box_autoadd_template_draft_view(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UndoToken sse_decode_box_autoadd_undo_token(SseDeserializer deserializer);

  @protected
  WallTime sse_decode_box_autoadd_wall_time(SseDeserializer deserializer);

  @protected
  BudgetSettings sse_decode_budget_settings(SseDeserializer deserializer);

  @protected
  CandidateView sse_decode_candidate_view(SseDeserializer deserializer);

  @protected
  CatBudgetView sse_decode_cat_budget_view(SseDeserializer deserializer);

  @protected
  CatLabel sse_decode_cat_label(SseDeserializer deserializer);

  @protected
  CategoryView sse_decode_category_view(SseDeserializer deserializer);

  @protected
  ChartPoint sse_decode_chart_point(SseDeserializer deserializer);

  @protected
  ChartView sse_decode_chart_view(SseDeserializer deserializer);

  @protected
  ClaimList sse_decode_claim_list(SseDeserializer deserializer);

  @protected
  ClaimView sse_decode_claim_view(SseDeserializer deserializer);

  @protected
  DrainSummary sse_decode_drain_summary(SseDeserializer deserializer);

  @protected
  DueView sse_decode_due_view(SseDeserializer deserializer);

  @protected
  EntryPatch sse_decode_entry_patch(SseDeserializer deserializer);

  @protected
  EntryView sse_decode_entry_view(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FormView sse_decode_form_view(SseDeserializer deserializer);

  @protected
  GlassLevel sse_decode_glass_level(SseDeserializer deserializer);

  @protected
  GlassSpec sse_decode_glass_spec(SseDeserializer deserializer);

  @protected
  GlassTier sse_decode_glass_tier(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImportPreview sse_decode_import_preview(SseDeserializer deserializer);

  @protected
  InsightCopyView sse_decode_insight_copy_view(SseDeserializer deserializer);

  @protected
  InsightView sse_decode_insight_view(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AccountBalance> sse_decode_list_account_balance(
    SseDeserializer deserializer,
  );

  @protected
  List<AccountView> sse_decode_list_account_view(SseDeserializer deserializer);

  @protected
  List<AcctRowView> sse_decode_list_acct_row_view(SseDeserializer deserializer);

  @protected
  List<AssetView> sse_decode_list_asset_view(SseDeserializer deserializer);

  @protected
  List<BackupInfoView> sse_decode_list_backup_info_view(
    SseDeserializer deserializer,
  );

  @protected
  List<CandidateView> sse_decode_list_candidate_view(
    SseDeserializer deserializer,
  );

  @protected
  List<CatBudgetView> sse_decode_list_cat_budget_view(
    SseDeserializer deserializer,
  );

  @protected
  List<CategoryView> sse_decode_list_category_view(
    SseDeserializer deserializer,
  );

  @protected
  List<ChartPoint> sse_decode_list_chart_point(SseDeserializer deserializer);

  @protected
  List<ClaimView> sse_decode_list_claim_view(SseDeserializer deserializer);

  @protected
  List<DueView> sse_decode_list_due_view(SseDeserializer deserializer);

  @protected
  List<EntryView> sse_decode_list_entry_view(SseDeserializer deserializer);

  @protected
  ListItem sse_decode_list_item(SseDeserializer deserializer);

  @protected
  List<ListItem> sse_decode_list_list_item(SseDeserializer deserializer);

  @protected
  List<LoanView> sse_decode_list_loan_view(SseDeserializer deserializer);

  @protected
  List<LockAction> sse_decode_list_lock_action(SseDeserializer deserializer);

  @protected
  List<PendingView> sse_decode_list_pending_view(SseDeserializer deserializer);

  @protected
  List<double> sse_decode_list_prim_f_64_loose(SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RateView> sse_decode_list_rate_view(SseDeserializer deserializer);

  @protected
  List<RawNotifView> sse_decode_list_raw_notif_view(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, double)> sse_decode_list_record_string_f_64(
    SseDeserializer deserializer,
  );

  @protected
  List<RowErrorView> sse_decode_list_row_error_view(
    SseDeserializer deserializer,
  );

  @protected
  List<ScheduleView> sse_decode_list_schedule_view(
    SseDeserializer deserializer,
  );

  @protected
  List<SliceView> sse_decode_list_slice_view(SseDeserializer deserializer);

  @protected
  List<SubView> sse_decode_list_sub_view(SseDeserializer deserializer);

  @protected
  List<TemplateView> sse_decode_list_template_view(
    SseDeserializer deserializer,
  );

  @protected
  List<ThemeOption> sse_decode_list_theme_option(SseDeserializer deserializer);

  @protected
  List<TrendPointView> sse_decode_list_trend_point_view(
    SseDeserializer deserializer,
  );

  @protected
  List<UnparsedView> sse_decode_list_unparsed_view(
    SseDeserializer deserializer,
  );

  @protected
  LoanView sse_decode_loan_view(SseDeserializer deserializer);

  @protected
  LockAction sse_decode_lock_action(SseDeserializer deserializer);

  @protected
  NetWorthView sse_decode_net_worth_view(SseDeserializer deserializer);

  @protected
  NewEntry sse_decode_new_entry(SseDeserializer deserializer);

  @protected
  NewSub sse_decode_new_sub(SseDeserializer deserializer);

  @protected
  NewTransfer sse_decode_new_transfer(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  EntryView? sse_decode_opt_box_autoadd_entry_view(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  InsightView? sse_decode_opt_box_autoadd_insight_view(
    SseDeserializer deserializer,
  );

  @protected
  RefundState? sse_decode_opt_box_autoadd_refund_state(
    SseDeserializer deserializer,
  );

  @protected
  StatementView? sse_decode_opt_box_autoadd_statement_view(
    SseDeserializer deserializer,
  );

  @protected
  TemplateDraftView? sse_decode_opt_box_autoadd_template_draft_view(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UndoToken? sse_decode_opt_box_autoadd_undo_token(
    SseDeserializer deserializer,
  );

  @protected
  WallTime? sse_decode_opt_box_autoadd_wall_time(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  OverviewView sse_decode_overview_view(SseDeserializer deserializer);

  @protected
  ParsedQueryView sse_decode_parsed_query_view(SseDeserializer deserializer);

  @protected
  PendingCharges sse_decode_pending_charges(SseDeserializer deserializer);

  @protected
  PendingView sse_decode_pending_view(SseDeserializer deserializer);

  @protected
  RateView sse_decode_rate_view(SseDeserializer deserializer);

  @protected
  RawNotifView sse_decode_raw_notif_view(SseDeserializer deserializer);

  @protected
  RecapView sse_decode_recap_view(SseDeserializer deserializer);

  @protected
  (String, double) sse_decode_record_string_f_64(SseDeserializer deserializer);

  @protected
  RefundState sse_decode_refund_state(SseDeserializer deserializer);

  @protected
  ResolvedRate sse_decode_resolved_rate(SseDeserializer deserializer);

  @protected
  RestoreResult sse_decode_restore_result(SseDeserializer deserializer);

  @protected
  RowErrorView sse_decode_row_error_view(SseDeserializer deserializer);

  @protected
  SaveResult sse_decode_save_result(SseDeserializer deserializer);

  @protected
  ScheduleView sse_decode_schedule_view(SseDeserializer deserializer);

  @protected
  SettingsView sse_decode_settings_view(SseDeserializer deserializer);

  @protected
  SliceView sse_decode_slice_view(SseDeserializer deserializer);

  @protected
  StatementView sse_decode_statement_view(SseDeserializer deserializer);

  @protected
  SubView sse_decode_sub_view(SseDeserializer deserializer);

  @protected
  SyncReport sse_decode_sync_report(SseDeserializer deserializer);

  @protected
  TemplateDraftView sse_decode_template_draft_view(
    SseDeserializer deserializer,
  );

  @protected
  TemplateView sse_decode_template_view(SseDeserializer deserializer);

  @protected
  ThemeOption sse_decode_theme_option(SseDeserializer deserializer);

  @protected
  ThemeView sse_decode_theme_view(SseDeserializer deserializer);

  @protected
  TierView sse_decode_tier_view(SseDeserializer deserializer);

  @protected
  TrendPointView sse_decode_trend_point_view(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UndoToken sse_decode_undo_token(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UnparsedView sse_decode_unparsed_view(SseDeserializer deserializer);

  @protected
  WallTime sse_decode_wall_time(SseDeserializer deserializer);

  @protected
  WeeklyView sse_decode_weekly_view(SseDeserializer deserializer);

  @protected
  WindowView sse_decode_window_view(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_balance(
    AccountBalance self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_account_view(AccountView self, SseSerializer serializer);

  @protected
  void sse_encode_acct_row_view(AcctRowView self, SseSerializer serializer);

  @protected
  void sse_encode_asset_view(AssetView self, SseSerializer serializer);

  @protected
  void sse_encode_backup_info_view(
    BackupInfoView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_category_view(
    CategoryView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_entry_patch(
    EntryPatch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_entry_view(
    EntryView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_form_view(
    FormView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_insight_copy_view(
    InsightCopyView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_insight_view(
    InsightView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_new_entry(
    NewEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_new_sub(NewSub self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_new_transfer(
    NewTransfer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_refund_state(
    RefundState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_settings_view(
    SettingsView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_statement_view(
    StatementView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_template_draft_view(
    TemplateDraftView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_undo_token(
    UndoToken self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wall_time(
    WallTime self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_budget_settings(
    BudgetSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_candidate_view(CandidateView self, SseSerializer serializer);

  @protected
  void sse_encode_cat_budget_view(CatBudgetView self, SseSerializer serializer);

  @protected
  void sse_encode_cat_label(CatLabel self, SseSerializer serializer);

  @protected
  void sse_encode_category_view(CategoryView self, SseSerializer serializer);

  @protected
  void sse_encode_chart_point(ChartPoint self, SseSerializer serializer);

  @protected
  void sse_encode_chart_view(ChartView self, SseSerializer serializer);

  @protected
  void sse_encode_claim_list(ClaimList self, SseSerializer serializer);

  @protected
  void sse_encode_claim_view(ClaimView self, SseSerializer serializer);

  @protected
  void sse_encode_drain_summary(DrainSummary self, SseSerializer serializer);

  @protected
  void sse_encode_due_view(DueView self, SseSerializer serializer);

  @protected
  void sse_encode_entry_patch(EntryPatch self, SseSerializer serializer);

  @protected
  void sse_encode_entry_view(EntryView self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_form_view(FormView self, SseSerializer serializer);

  @protected
  void sse_encode_glass_level(GlassLevel self, SseSerializer serializer);

  @protected
  void sse_encode_glass_spec(GlassSpec self, SseSerializer serializer);

  @protected
  void sse_encode_glass_tier(GlassTier self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_import_preview(ImportPreview self, SseSerializer serializer);

  @protected
  void sse_encode_insight_copy_view(
    InsightCopyView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_insight_view(InsightView self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_account_balance(
    List<AccountBalance> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_account_view(
    List<AccountView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_acct_row_view(
    List<AcctRowView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_asset_view(
    List<AssetView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_backup_info_view(
    List<BackupInfoView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_candidate_view(
    List<CandidateView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_cat_budget_view(
    List<CatBudgetView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_category_view(
    List<CategoryView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chart_point(
    List<ChartPoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_claim_view(
    List<ClaimView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_due_view(List<DueView> self, SseSerializer serializer);

  @protected
  void sse_encode_list_entry_view(
    List<EntryView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_item(ListItem self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_item(List<ListItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_loan_view(List<LoanView> self, SseSerializer serializer);

  @protected
  void sse_encode_list_lock_action(
    List<LockAction> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pending_view(
    List<PendingView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_64_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rate_view(List<RateView> self, SseSerializer serializer);

  @protected
  void sse_encode_list_raw_notif_view(
    List<RawNotifView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_f_64(
    List<(String, double)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_row_error_view(
    List<RowErrorView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_schedule_view(
    List<ScheduleView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_slice_view(
    List<SliceView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sub_view(List<SubView> self, SseSerializer serializer);

  @protected
  void sse_encode_list_template_view(
    List<TemplateView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_theme_option(
    List<ThemeOption> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_trend_point_view(
    List<TrendPointView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_unparsed_view(
    List<UnparsedView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_loan_view(LoanView self, SseSerializer serializer);

  @protected
  void sse_encode_lock_action(LockAction self, SseSerializer serializer);

  @protected
  void sse_encode_net_worth_view(NetWorthView self, SseSerializer serializer);

  @protected
  void sse_encode_new_entry(NewEntry self, SseSerializer serializer);

  @protected
  void sse_encode_new_sub(NewSub self, SseSerializer serializer);

  @protected
  void sse_encode_new_transfer(NewTransfer self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_entry_view(
    EntryView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_insight_view(
    InsightView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_refund_state(
    RefundState? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_statement_view(
    StatementView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_template_draft_view(
    TemplateDraftView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_undo_token(
    UndoToken? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_wall_time(
    WallTime? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_overview_view(OverviewView self, SseSerializer serializer);

  @protected
  void sse_encode_parsed_query_view(
    ParsedQueryView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pending_charges(
    PendingCharges self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pending_view(PendingView self, SseSerializer serializer);

  @protected
  void sse_encode_rate_view(RateView self, SseSerializer serializer);

  @protected
  void sse_encode_raw_notif_view(RawNotifView self, SseSerializer serializer);

  @protected
  void sse_encode_recap_view(RecapView self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_f_64(
    (String, double) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_refund_state(RefundState self, SseSerializer serializer);

  @protected
  void sse_encode_resolved_rate(ResolvedRate self, SseSerializer serializer);

  @protected
  void sse_encode_restore_result(RestoreResult self, SseSerializer serializer);

  @protected
  void sse_encode_row_error_view(RowErrorView self, SseSerializer serializer);

  @protected
  void sse_encode_save_result(SaveResult self, SseSerializer serializer);

  @protected
  void sse_encode_schedule_view(ScheduleView self, SseSerializer serializer);

  @protected
  void sse_encode_settings_view(SettingsView self, SseSerializer serializer);

  @protected
  void sse_encode_slice_view(SliceView self, SseSerializer serializer);

  @protected
  void sse_encode_statement_view(StatementView self, SseSerializer serializer);

  @protected
  void sse_encode_sub_view(SubView self, SseSerializer serializer);

  @protected
  void sse_encode_sync_report(SyncReport self, SseSerializer serializer);

  @protected
  void sse_encode_template_draft_view(
    TemplateDraftView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_template_view(TemplateView self, SseSerializer serializer);

  @protected
  void sse_encode_theme_option(ThemeOption self, SseSerializer serializer);

  @protected
  void sse_encode_theme_view(ThemeView self, SseSerializer serializer);

  @protected
  void sse_encode_tier_view(TierView self, SseSerializer serializer);

  @protected
  void sse_encode_trend_point_view(
    TrendPointView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_undo_token(UndoToken self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_unparsed_view(UnparsedView self, SseSerializer serializer);

  @protected
  void sse_encode_wall_time(WallTime self, SseSerializer serializer);

  @protected
  void sse_encode_weekly_view(WeeklyView self, SseSerializer serializer);

  @protected
  void sse_encode_window_view(WindowView self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
