// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/accounts.dart';
import 'api/budget.dart';
import 'api/calc.dart';
import 'api/catalog.dart';
import 'api/glass.dart';
import 'api/money.dart';
import 'api/networth.dart';
import 'api/record.dart';
import 'api/stats.dart';
import 'api/store.dart';
import 'api/subscriptions.dart';
import 'api/sync.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountBalance dco_decode_account_balance(dynamic raw);

  @protected
  AccountView dco_decode_account_view(dynamic raw);

  @protected
  AssetView dco_decode_asset_view(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  CategoryView dco_decode_box_autoadd_category_view(dynamic raw);

  @protected
  EntryPatch dco_decode_box_autoadd_entry_patch(dynamic raw);

  @protected
  EntryView dco_decode_box_autoadd_entry_view(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  FormView dco_decode_box_autoadd_form_view(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  NewEntry dco_decode_box_autoadd_new_entry(dynamic raw);

  @protected
  NewSub dco_decode_box_autoadd_new_sub(dynamic raw);

  @protected
  NewTransfer dco_decode_box_autoadd_new_transfer(dynamic raw);

  @protected
  SettingsView dco_decode_box_autoadd_settings_view(dynamic raw);

  @protected
  TemplateDraftView dco_decode_box_autoadd_template_draft_view(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  UndoToken dco_decode_box_autoadd_undo_token(dynamic raw);

  @protected
  BudgetSettings dco_decode_budget_settings(dynamic raw);

  @protected
  CatBudgetView dco_decode_cat_budget_view(dynamic raw);

  @protected
  CatLabel dco_decode_cat_label(dynamic raw);

  @protected
  CategoryView dco_decode_category_view(dynamic raw);

  @protected
  ChartPoint dco_decode_chart_point(dynamic raw);

  @protected
  ChartView dco_decode_chart_view(dynamic raw);

  @protected
  EntryPatch dco_decode_entry_patch(dynamic raw);

  @protected
  EntryView dco_decode_entry_view(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FormView dco_decode_form_view(dynamic raw);

  @protected
  GlassLevel dco_decode_glass_level(dynamic raw);

  @protected
  GlassSpec dco_decode_glass_spec(dynamic raw);

  @protected
  GlassTier dco_decode_glass_tier(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AccountBalance> dco_decode_list_account_balance(dynamic raw);

  @protected
  List<AccountView> dco_decode_list_account_view(dynamic raw);

  @protected
  List<AssetView> dco_decode_list_asset_view(dynamic raw);

  @protected
  List<CatBudgetView> dco_decode_list_cat_budget_view(dynamic raw);

  @protected
  List<CategoryView> dco_decode_list_category_view(dynamic raw);

  @protected
  List<ChartPoint> dco_decode_list_chart_point(dynamic raw);

  @protected
  List<EntryView> dco_decode_list_entry_view(dynamic raw);

  @protected
  ListItem dco_decode_list_item(dynamic raw);

  @protected
  List<ListItem> dco_decode_list_list_item(dynamic raw);

  @protected
  List<LoanView> dco_decode_list_loan_view(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_64_loose(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, double)> dco_decode_list_record_string_f_64(dynamic raw);

  @protected
  List<SliceView> dco_decode_list_slice_view(dynamic raw);

  @protected
  List<SubView> dco_decode_list_sub_view(dynamic raw);

  @protected
  List<SyncEffect> dco_decode_list_sync_effect(dynamic raw);

  @protected
  List<TemplateView> dco_decode_list_template_view(dynamic raw);

  @protected
  List<TrendPointView> dco_decode_list_trend_point_view(dynamic raw);

  @protected
  LoanView dco_decode_loan_view(dynamic raw);

  @protected
  NetWorthView dco_decode_net_worth_view(dynamic raw);

  @protected
  NewEntry dco_decode_new_entry(dynamic raw);

  @protected
  NewSub dco_decode_new_sub(dynamic raw);

  @protected
  NewTransfer dco_decode_new_transfer(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  EntryView? dco_decode_opt_box_autoadd_entry_view(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  TemplateDraftView? dco_decode_opt_box_autoadd_template_draft_view(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  UndoToken? dco_decode_opt_box_autoadd_undo_token(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  OverviewView dco_decode_overview_view(dynamic raw);

  @protected
  PendingCharges dco_decode_pending_charges(dynamic raw);

  @protected
  (String, double) dco_decode_record_string_f_64(dynamic raw);

  @protected
  SaveResult dco_decode_save_result(dynamic raw);

  @protected
  SettingsView dco_decode_settings_view(dynamic raw);

  @protected
  SliceView dco_decode_slice_view(dynamic raw);

  @protected
  SubView dco_decode_sub_view(dynamic raw);

  @protected
  SyncEffect dco_decode_sync_effect(dynamic raw);

  @protected
  TemplateDraftView dco_decode_template_draft_view(dynamic raw);

  @protected
  TemplateView dco_decode_template_view(dynamic raw);

  @protected
  TierView dco_decode_tier_view(dynamic raw);

  @protected
  TrendPointView dco_decode_trend_point_view(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UndoToken dco_decode_undo_token(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountBalance sse_decode_account_balance(SseDeserializer deserializer);

  @protected
  AccountView sse_decode_account_view(SseDeserializer deserializer);

  @protected
  AssetView sse_decode_asset_view(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CategoryView sse_decode_box_autoadd_category_view(
    SseDeserializer deserializer,
  );

  @protected
  EntryPatch sse_decode_box_autoadd_entry_patch(SseDeserializer deserializer);

  @protected
  EntryView sse_decode_box_autoadd_entry_view(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FormView sse_decode_box_autoadd_form_view(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  NewEntry sse_decode_box_autoadd_new_entry(SseDeserializer deserializer);

  @protected
  NewSub sse_decode_box_autoadd_new_sub(SseDeserializer deserializer);

  @protected
  NewTransfer sse_decode_box_autoadd_new_transfer(SseDeserializer deserializer);

  @protected
  SettingsView sse_decode_box_autoadd_settings_view(
    SseDeserializer deserializer,
  );

  @protected
  TemplateDraftView sse_decode_box_autoadd_template_draft_view(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UndoToken sse_decode_box_autoadd_undo_token(SseDeserializer deserializer);

  @protected
  BudgetSettings sse_decode_budget_settings(SseDeserializer deserializer);

  @protected
  CatBudgetView sse_decode_cat_budget_view(SseDeserializer deserializer);

  @protected
  CatLabel sse_decode_cat_label(SseDeserializer deserializer);

  @protected
  CategoryView sse_decode_category_view(SseDeserializer deserializer);

  @protected
  ChartPoint sse_decode_chart_point(SseDeserializer deserializer);

  @protected
  ChartView sse_decode_chart_view(SseDeserializer deserializer);

  @protected
  EntryPatch sse_decode_entry_patch(SseDeserializer deserializer);

  @protected
  EntryView sse_decode_entry_view(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FormView sse_decode_form_view(SseDeserializer deserializer);

  @protected
  GlassLevel sse_decode_glass_level(SseDeserializer deserializer);

  @protected
  GlassSpec sse_decode_glass_spec(SseDeserializer deserializer);

  @protected
  GlassTier sse_decode_glass_tier(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AccountBalance> sse_decode_list_account_balance(
    SseDeserializer deserializer,
  );

  @protected
  List<AccountView> sse_decode_list_account_view(SseDeserializer deserializer);

  @protected
  List<AssetView> sse_decode_list_asset_view(SseDeserializer deserializer);

  @protected
  List<CatBudgetView> sse_decode_list_cat_budget_view(
    SseDeserializer deserializer,
  );

  @protected
  List<CategoryView> sse_decode_list_category_view(
    SseDeserializer deserializer,
  );

  @protected
  List<ChartPoint> sse_decode_list_chart_point(SseDeserializer deserializer);

  @protected
  List<EntryView> sse_decode_list_entry_view(SseDeserializer deserializer);

  @protected
  ListItem sse_decode_list_item(SseDeserializer deserializer);

  @protected
  List<ListItem> sse_decode_list_list_item(SseDeserializer deserializer);

  @protected
  List<LoanView> sse_decode_list_loan_view(SseDeserializer deserializer);

  @protected
  List<double> sse_decode_list_prim_f_64_loose(SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, double)> sse_decode_list_record_string_f_64(
    SseDeserializer deserializer,
  );

  @protected
  List<SliceView> sse_decode_list_slice_view(SseDeserializer deserializer);

  @protected
  List<SubView> sse_decode_list_sub_view(SseDeserializer deserializer);

  @protected
  List<SyncEffect> sse_decode_list_sync_effect(SseDeserializer deserializer);

  @protected
  List<TemplateView> sse_decode_list_template_view(
    SseDeserializer deserializer,
  );

  @protected
  List<TrendPointView> sse_decode_list_trend_point_view(
    SseDeserializer deserializer,
  );

  @protected
  LoanView sse_decode_loan_view(SseDeserializer deserializer);

  @protected
  NetWorthView sse_decode_net_worth_view(SseDeserializer deserializer);

  @protected
  NewEntry sse_decode_new_entry(SseDeserializer deserializer);

  @protected
  NewSub sse_decode_new_sub(SseDeserializer deserializer);

  @protected
  NewTransfer sse_decode_new_transfer(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  EntryView? sse_decode_opt_box_autoadd_entry_view(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  TemplateDraftView? sse_decode_opt_box_autoadd_template_draft_view(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UndoToken? sse_decode_opt_box_autoadd_undo_token(
    SseDeserializer deserializer,
  );

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  OverviewView sse_decode_overview_view(SseDeserializer deserializer);

  @protected
  PendingCharges sse_decode_pending_charges(SseDeserializer deserializer);

  @protected
  (String, double) sse_decode_record_string_f_64(SseDeserializer deserializer);

  @protected
  SaveResult sse_decode_save_result(SseDeserializer deserializer);

  @protected
  SettingsView sse_decode_settings_view(SseDeserializer deserializer);

  @protected
  SliceView sse_decode_slice_view(SseDeserializer deserializer);

  @protected
  SubView sse_decode_sub_view(SseDeserializer deserializer);

  @protected
  SyncEffect sse_decode_sync_effect(SseDeserializer deserializer);

  @protected
  TemplateDraftView sse_decode_template_draft_view(
    SseDeserializer deserializer,
  );

  @protected
  TemplateView sse_decode_template_view(SseDeserializer deserializer);

  @protected
  TierView sse_decode_tier_view(SseDeserializer deserializer);

  @protected
  TrendPointView sse_decode_trend_point_view(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UndoToken sse_decode_undo_token(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_balance(
    AccountBalance self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_account_view(AccountView self, SseSerializer serializer);

  @protected
  void sse_encode_asset_view(AssetView self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_category_view(
    CategoryView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_entry_patch(
    EntryPatch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_entry_view(
    EntryView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_form_view(
    FormView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_new_entry(
    NewEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_new_sub(NewSub self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_new_transfer(
    NewTransfer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_settings_view(
    SettingsView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_template_draft_view(
    TemplateDraftView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_undo_token(
    UndoToken self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_budget_settings(
    BudgetSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cat_budget_view(CatBudgetView self, SseSerializer serializer);

  @protected
  void sse_encode_cat_label(CatLabel self, SseSerializer serializer);

  @protected
  void sse_encode_category_view(CategoryView self, SseSerializer serializer);

  @protected
  void sse_encode_chart_point(ChartPoint self, SseSerializer serializer);

  @protected
  void sse_encode_chart_view(ChartView self, SseSerializer serializer);

  @protected
  void sse_encode_entry_patch(EntryPatch self, SseSerializer serializer);

  @protected
  void sse_encode_entry_view(EntryView self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_form_view(FormView self, SseSerializer serializer);

  @protected
  void sse_encode_glass_level(GlassLevel self, SseSerializer serializer);

  @protected
  void sse_encode_glass_spec(GlassSpec self, SseSerializer serializer);

  @protected
  void sse_encode_glass_tier(GlassTier self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_account_balance(
    List<AccountBalance> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_account_view(
    List<AccountView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_asset_view(
    List<AssetView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_cat_budget_view(
    List<CatBudgetView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_category_view(
    List<CategoryView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chart_point(
    List<ChartPoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_entry_view(
    List<EntryView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_item(ListItem self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_item(List<ListItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_loan_view(List<LoanView> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_64_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_f_64(
    List<(String, double)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_slice_view(
    List<SliceView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sub_view(List<SubView> self, SseSerializer serializer);

  @protected
  void sse_encode_list_sync_effect(
    List<SyncEffect> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_template_view(
    List<TemplateView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_trend_point_view(
    List<TrendPointView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_loan_view(LoanView self, SseSerializer serializer);

  @protected
  void sse_encode_net_worth_view(NetWorthView self, SseSerializer serializer);

  @protected
  void sse_encode_new_entry(NewEntry self, SseSerializer serializer);

  @protected
  void sse_encode_new_sub(NewSub self, SseSerializer serializer);

  @protected
  void sse_encode_new_transfer(NewTransfer self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_entry_view(
    EntryView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_template_draft_view(
    TemplateDraftView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_undo_token(
    UndoToken? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_overview_view(OverviewView self, SseSerializer serializer);

  @protected
  void sse_encode_pending_charges(
    PendingCharges self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_f_64(
    (String, double) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_save_result(SaveResult self, SseSerializer serializer);

  @protected
  void sse_encode_settings_view(SettingsView self, SseSerializer serializer);

  @protected
  void sse_encode_slice_view(SliceView self, SseSerializer serializer);

  @protected
  void sse_encode_sub_view(SubView self, SseSerializer serializer);

  @protected
  void sse_encode_sync_effect(SyncEffect self, SseSerializer serializer);

  @protected
  void sse_encode_template_draft_view(
    TemplateDraftView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_template_view(TemplateView self, SseSerializer serializer);

  @protected
  void sse_encode_tier_view(TierView self, SseSerializer serializer);

  @protected
  void sse_encode_trend_point_view(
    TrendPointView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_undo_token(UndoToken self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
