// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/calc.dart';
import 'api/catalog.dart';
import 'api/glass.dart';
import 'api/money.dart';
import 'api/store.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountView dco_decode_account_view(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  CategoryView dco_decode_box_autoadd_category_view(dynamic raw);

  @protected
  EntryPatch dco_decode_box_autoadd_entry_patch(dynamic raw);

  @protected
  EntryView dco_decode_box_autoadd_entry_view(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  NewEntry dco_decode_box_autoadd_new_entry(dynamic raw);

  @protected
  NewTransfer dco_decode_box_autoadd_new_transfer(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  UndoToken dco_decode_box_autoadd_undo_token(dynamic raw);

  @protected
  CatLabel dco_decode_cat_label(dynamic raw);

  @protected
  CategoryView dco_decode_category_view(dynamic raw);

  @protected
  EntryPatch dco_decode_entry_patch(dynamic raw);

  @protected
  EntryView dco_decode_entry_view(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GlassLevel dco_decode_glass_level(dynamic raw);

  @protected
  GlassSpec dco_decode_glass_spec(dynamic raw);

  @protected
  GlassTier dco_decode_glass_tier(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AccountView> dco_decode_list_account_view(dynamic raw);

  @protected
  List<CategoryView> dco_decode_list_category_view(dynamic raw);

  @protected
  List<EntryView> dco_decode_list_entry_view(dynamic raw);

  @protected
  ListItem dco_decode_list_item(dynamic raw);

  @protected
  List<ListItem> dco_decode_list_list_item(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_64_loose(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  NewEntry dco_decode_new_entry(dynamic raw);

  @protected
  NewTransfer dco_decode_new_transfer(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  EntryView? dco_decode_opt_box_autoadd_entry_view(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  UndoToken? dco_decode_opt_box_autoadd_undo_token(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UndoToken dco_decode_undo_token(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountView sse_decode_account_view(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CategoryView sse_decode_box_autoadd_category_view(
    SseDeserializer deserializer,
  );

  @protected
  EntryPatch sse_decode_box_autoadd_entry_patch(SseDeserializer deserializer);

  @protected
  EntryView sse_decode_box_autoadd_entry_view(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  NewEntry sse_decode_box_autoadd_new_entry(SseDeserializer deserializer);

  @protected
  NewTransfer sse_decode_box_autoadd_new_transfer(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UndoToken sse_decode_box_autoadd_undo_token(SseDeserializer deserializer);

  @protected
  CatLabel sse_decode_cat_label(SseDeserializer deserializer);

  @protected
  CategoryView sse_decode_category_view(SseDeserializer deserializer);

  @protected
  EntryPatch sse_decode_entry_patch(SseDeserializer deserializer);

  @protected
  EntryView sse_decode_entry_view(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GlassLevel sse_decode_glass_level(SseDeserializer deserializer);

  @protected
  GlassSpec sse_decode_glass_spec(SseDeserializer deserializer);

  @protected
  GlassTier sse_decode_glass_tier(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AccountView> sse_decode_list_account_view(SseDeserializer deserializer);

  @protected
  List<CategoryView> sse_decode_list_category_view(
    SseDeserializer deserializer,
  );

  @protected
  List<EntryView> sse_decode_list_entry_view(SseDeserializer deserializer);

  @protected
  ListItem sse_decode_list_item(SseDeserializer deserializer);

  @protected
  List<ListItem> sse_decode_list_list_item(SseDeserializer deserializer);

  @protected
  List<double> sse_decode_list_prim_f_64_loose(SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  NewEntry sse_decode_new_entry(SseDeserializer deserializer);

  @protected
  NewTransfer sse_decode_new_transfer(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  EntryView? sse_decode_opt_box_autoadd_entry_view(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UndoToken? sse_decode_opt_box_autoadd_undo_token(
    SseDeserializer deserializer,
  );

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UndoToken sse_decode_undo_token(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_view(AccountView self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_category_view(
    CategoryView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_entry_patch(
    EntryPatch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_entry_view(
    EntryView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_new_entry(
    NewEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_new_transfer(
    NewTransfer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_undo_token(
    UndoToken self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cat_label(CatLabel self, SseSerializer serializer);

  @protected
  void sse_encode_category_view(CategoryView self, SseSerializer serializer);

  @protected
  void sse_encode_entry_patch(EntryPatch self, SseSerializer serializer);

  @protected
  void sse_encode_entry_view(EntryView self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_glass_level(GlassLevel self, SseSerializer serializer);

  @protected
  void sse_encode_glass_spec(GlassSpec self, SseSerializer serializer);

  @protected
  void sse_encode_glass_tier(GlassTier self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_account_view(
    List<AccountView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_category_view(
    List<CategoryView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_entry_view(
    List<EntryView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_item(ListItem self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_item(List<ListItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_64_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_new_entry(NewEntry self, SseSerializer serializer);

  @protected
  void sse_encode_new_transfer(NewTransfer self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_entry_view(
    EntryView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_undo_token(
    UndoToken? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_undo_token(UndoToken self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
