// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/calc.dart';
import 'api/glass.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1465871447;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'dahonghua_bridge',
        ioDirectory: 'rust_bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiCalcApplyKey({required String expr, required String key});

  double crateApiCalcEvalExpr({required String expr});

  GlassSpec crateApiGlassGlassSpec({
    required bool isDark,
    required GlassLevel level,
  });

  bool crateApiCalcHasOperator({required String expr});

  Future<void> crateApiInitInitApp();

  double crateApiGlassLuminance({required String hex});

  double crateApiGlassReadabilityAlpha({
    required bool isDark,
    required GlassLevel level,
    required double density,
    required GlassTier tier,
  });

  GlassTier crateApiGlassResolveTier({
    required bool reduceTransparency,
    required bool isWeb,
  });

  String crateApiGlassTouchLightColor({required bool isDark});

  String crateApiGlassWashColor({
    required bool isDark,
    required String card,
    required String paper,
    required GlassLevel level,
    String? under,
    double? alpha,
    String? surface,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiCalcApplyKey({required String expr, required String key}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(expr, serializer);
          sse_encode_String(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCalcApplyKeyConstMeta,
        argValues: [expr, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalcApplyKeyConstMeta =>
      const TaskConstMeta(debugName: "apply_key", argNames: ["expr", "key"]);

  @override
  double crateApiCalcEvalExpr({required String expr}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(expr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCalcEvalExprConstMeta,
        argValues: [expr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalcEvalExprConstMeta =>
      const TaskConstMeta(debugName: "eval_expr", argNames: ["expr"]);

  @override
  GlassSpec crateApiGlassGlassSpec({
    required bool isDark,
    required GlassLevel level,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(isDark, serializer);
          sse_encode_glass_level(level, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_glass_spec,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGlassGlassSpecConstMeta,
        argValues: [isDark, level],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGlassGlassSpecConstMeta => const TaskConstMeta(
    debugName: "glass_spec",
    argNames: ["isDark", "level"],
  );

  @override
  bool crateApiCalcHasOperator({required String expr}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(expr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCalcHasOperatorConstMeta,
        argValues: [expr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalcHasOperatorConstMeta =>
      const TaskConstMeta(debugName: "has_operator", argNames: ["expr"]);

  @override
  Future<void> crateApiInitInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  double crateApiGlassLuminance({required String hex}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGlassLuminanceConstMeta,
        argValues: [hex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGlassLuminanceConstMeta =>
      const TaskConstMeta(debugName: "luminance", argNames: ["hex"]);

  @override
  double crateApiGlassReadabilityAlpha({
    required bool isDark,
    required GlassLevel level,
    required double density,
    required GlassTier tier,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(isDark, serializer);
          sse_encode_glass_level(level, serializer);
          sse_encode_f_64(density, serializer);
          sse_encode_glass_tier(tier, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGlassReadabilityAlphaConstMeta,
        argValues: [isDark, level, density, tier],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGlassReadabilityAlphaConstMeta =>
      const TaskConstMeta(
        debugName: "readability_alpha",
        argNames: ["isDark", "level", "density", "tier"],
      );

  @override
  GlassTier crateApiGlassResolveTier({
    required bool reduceTransparency,
    required bool isWeb,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(reduceTransparency, serializer);
          sse_encode_bool(isWeb, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_glass_tier,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGlassResolveTierConstMeta,
        argValues: [reduceTransparency, isWeb],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGlassResolveTierConstMeta => const TaskConstMeta(
    debugName: "resolve_tier",
    argNames: ["reduceTransparency", "isWeb"],
  );

  @override
  String crateApiGlassTouchLightColor({required bool isDark}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(isDark, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGlassTouchLightColorConstMeta,
        argValues: [isDark],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGlassTouchLightColorConstMeta =>
      const TaskConstMeta(debugName: "touch_light_color", argNames: ["isDark"]);

  @override
  String crateApiGlassWashColor({
    required bool isDark,
    required String card,
    required String paper,
    required GlassLevel level,
    String? under,
    double? alpha,
    String? surface,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(isDark, serializer);
          sse_encode_String(card, serializer);
          sse_encode_String(paper, serializer);
          sse_encode_glass_level(level, serializer);
          sse_encode_opt_String(under, serializer);
          sse_encode_opt_box_autoadd_f_64(alpha, serializer);
          sse_encode_opt_String(surface, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGlassWashColorConstMeta,
        argValues: [isDark, card, paper, level, under, alpha, surface],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGlassWashColorConstMeta => const TaskConstMeta(
    debugName: "wash_color",
    argNames: ["isDark", "card", "paper", "level", "under", "alpha", "surface"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GlassLevel dco_decode_glass_level(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GlassLevel.values[raw as int];
  }

  @protected
  GlassSpec dco_decode_glass_spec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return GlassSpec(
      intensity: dco_decode_f_64(arr[0]),
      washAlpha: dco_decode_f_64(arr[1]),
      washAlphaFlat: dco_decode_f_64(arr[2]),
      sheen: dco_decode_f_64(arr[3]),
      sheenHeight: dco_decode_f_64(arr[4]),
      edge: dco_decode_String(arr[5]),
      edgeWidth: dco_decode_f_64(arr[6]),
    );
  }

  @protected
  GlassTier dco_decode_glass_tier(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GlassTier.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  GlassLevel sse_decode_glass_level(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GlassLevel.values[inner];
  }

  @protected
  GlassSpec sse_decode_glass_spec(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_intensity = sse_decode_f_64(deserializer);
    var var_washAlpha = sse_decode_f_64(deserializer);
    var var_washAlphaFlat = sse_decode_f_64(deserializer);
    var var_sheen = sse_decode_f_64(deserializer);
    var var_sheenHeight = sse_decode_f_64(deserializer);
    var var_edge = sse_decode_String(deserializer);
    var var_edgeWidth = sse_decode_f_64(deserializer);
    return GlassSpec(
      intensity: var_intensity,
      washAlpha: var_washAlpha,
      washAlphaFlat: var_washAlphaFlat,
      sheen: var_sheen,
      sheenHeight: var_sheenHeight,
      edge: var_edge,
      edgeWidth: var_edgeWidth,
    );
  }

  @protected
  GlassTier sse_decode_glass_tier(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GlassTier.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_glass_level(GlassLevel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_glass_spec(GlassSpec self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.intensity, serializer);
    sse_encode_f_64(self.washAlpha, serializer);
    sse_encode_f_64(self.washAlphaFlat, serializer);
    sse_encode_f_64(self.sheen, serializer);
    sse_encode_f_64(self.sheenHeight, serializer);
    sse_encode_String(self.edge, serializer);
    sse_encode_f_64(self.edgeWidth, serializer);
  }

  @protected
  void sse_encode_glass_tier(GlassTier self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
